--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2
-- Dumped by pg_dump version 17.5

-- Started on 2025-09-08 00:13:20

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5216 (class 1262 OID 86495)
-- Name: PPTR_Bili_Lot; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "PPTR_Bili_Lot" WITH TEMPLATE = template0 ENCODING = 'UTF8' ICU_LOCALE = 'zh-CN' LOCALE_PROVIDER  = 'icu';


ALTER DATABASE "PPTR_Bili_Lot" OWNER TO postgres;

\connect "PPTR_Bili_Lot"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 276 (class 1255 OID 86496)
-- Name: 将createdAt、updatedAt默认值设置为current_timestamp(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public."将createdAt、updatedAt默认值设置为current_timestamp"() RETURNS integer
    LANGUAGE sql
    AS $_$DO $$ 
DECLARE
    table_record RECORD;
BEGIN
    FOR table_record IN 
        SELECT table_schema, table_name
        FROM information_schema.columns 
        WHERE column_name = 'createdAt' OR column_name = 'updatedAt'
        GROUP BY table_schema, table_name
        HAVING COUNT(DISTINCT column_name) = 2 -- 确保两个列都存在
        AND table_schema NOT IN ('pg_catalog', 'information_schema')
    LOOP
        -- 检查并确保列名是大小写敏感的
        IF EXISTS (
            SELECT 1
            FROM information_schema.columns 
            WHERE table_schema = table_record.table_schema
              AND table_name = table_record.table_name
              AND column_name = 'createdAt'
        ) AND EXISTS (
            SELECT 1
            FROM information_schema.columns 
            WHERE table_schema = table_record.table_schema
              AND table_name = table_record.table_name
              AND column_name = 'updatedAt'
        ) THEN
            -- 设置 createdAt 和 updatedAt 的默认值
            EXECUTE format(
                'ALTER TABLE %I.%I 
                 ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
                 ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;',
                table_record.table_schema, table_record.table_name
            );

            RAISE NOTICE 'Processed table: %.%', table_record.table_schema, table_record.table_name;
        ELSE
            RAISE WARNING 'Table %.% does not have both "createdAt" and "updatedAt" columns with correct case.', table_record.table_schema, table_record.table_name;
        END IF;
    END LOOP;
END $$;
select 1;$_$;


ALTER FUNCTION public."将createdAt、updatedAt默认值设置为current_timestamp"() OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 215 (class 1259 OID 86497)
-- Name: TAccountBiliAtMsg; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TAccountBiliAtMsg" (
    account_id integer,
    at_id bigint NOT NULL,
    item json,
    uid bigint,
    at_time integer,
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "deletedAt" timestamp with time zone
);


ALTER TABLE public."TAccountBiliAtMsg" OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 86504)
-- Name: TAccountBiliWhisperMsg; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TAccountBiliWhisperMsg" (
    account_id integer,
    msg_key bigint NOT NULL,
    msg_source integer,
    msg_type integer,
    notify_code character varying(255),
    receiver_id bigint,
    receiver_type integer,
    sender_uid bigint,
    "timestamp" integer,
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "deletedAt" timestamp with time zone
);


ALTER TABLE public."TAccountBiliWhisperMsg" OWNER TO postgres;

--
-- TOC entry 5217 (class 0 OID 0)
-- Dependencies: 216
-- Name: COLUMN "TAccountBiliWhisperMsg"."timestamp"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."TAccountBiliWhisperMsg"."timestamp" IS '消息时间戳（秒）';


--
-- TOC entry 217 (class 1259 OID 86509)
-- Name: TAccountBiliMsg_msg_key_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TAccountBiliWhisperMsg" ALTER COLUMN msg_key ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TAccountBiliMsg_msg_key_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 86510)
-- Name: TAccountBiliReplyMsg; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TAccountBiliReplyMsg" (
    account_id integer,
    reply_id bigint NOT NULL,
    counts integer,
    item json,
    reply_time integer,
    uid bigint,
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "deletedAt" timestamp with time zone
);


ALTER TABLE public."TAccountBiliReplyMsg" OWNER TO postgres;

--
-- TOC entry 5218 (class 0 OID 0)
-- Dependencies: 218
-- Name: COLUMN "TAccountBiliReplyMsg".reply_time; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."TAccountBiliReplyMsg".reply_time IS '回复的时间戳';


--
-- TOC entry 219 (class 1259 OID 86517)
-- Name: TAccountDetailInfo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TAccountDetailInfo" (
    account_detail_info_id integer NOT NULL,
    account_info_id integer,
    uname character varying(255),
    vip character varying(30) DEFAULT '普通用户'::character varying,
    level smallint DEFAULT 0,
    uid character varying(255),
    settings json,
    nav_json json,
    face character varying(255),
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "deletedAt" timestamp with time zone
);


ALTER TABLE public."TAccountDetailInfo" OWNER TO postgres;

--
-- TOC entry 5219 (class 0 OID 0)
-- Dependencies: 219
-- Name: COLUMN "TAccountDetailInfo".uname; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."TAccountDetailInfo".uname IS '账号的用户名（B站昵称）';


--
-- TOC entry 220 (class 1259 OID 86526)
-- Name: TAccountDetailInfo_account_detail_info_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TAccountDetailInfo" ALTER COLUMN account_detail_info_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TAccountDetailInfo_account_detail_info_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 86527)
-- Name: TAccountInfo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TAccountInfo" (
    account_name text,
    account_id integer NOT NULL,
    uid bigint,
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "deletedAt" timestamp with time zone
);


ALTER TABLE public."TAccountInfo" OWNER TO postgres;

--
-- TOC entry 5220 (class 0 OID 0)
-- Dependencies: 221
-- Name: COLUMN "TAccountInfo".account_name; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."TAccountInfo".account_name IS '账号名称，非b站的昵称';


--
-- TOC entry 5221 (class 0 OID 0)
-- Dependencies: 221
-- Name: COLUMN "TAccountInfo".account_id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."TAccountInfo".account_id IS '账户id，自增主键';


--
-- TOC entry 5222 (class 0 OID 0)
-- Dependencies: 221
-- Name: COLUMN "TAccountInfo".uid; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."TAccountInfo".uid IS '本系统的用户id';


--
-- TOC entry 222 (class 1259 OID 86534)
-- Name: TAccountInfo_DashBoardInfo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TAccountInfo_DashBoardInfo" (
    dashboard_id integer NOT NULL,
    accountinfo_id integer,
    account_uid text,
    account_uname text,
    level integer,
    account_status text,
    latest_lot_timestamp integer,
    vip character varying(30),
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "deletedAt" timestamp with time zone
);


ALTER TABLE public."TAccountInfo_DashBoardInfo" OWNER TO postgres;

--
-- TOC entry 5223 (class 0 OID 0)
-- Dependencies: 222
-- Name: COLUMN "TAccountInfo_DashBoardInfo".accountinfo_id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."TAccountInfo_DashBoardInfo".accountinfo_id IS 'accountinfo的外键';


--
-- TOC entry 5224 (class 0 OID 0)
-- Dependencies: 222
-- Name: COLUMN "TAccountInfo_DashBoardInfo".vip; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."TAccountInfo_DashBoardInfo".vip IS 'vip等级（普通用户，月度大会员，年度大会员，十年大会员，百年大会员';


--
-- TOC entry 223 (class 1259 OID 86541)
-- Name: TAccountInfo_DashBoardInfo_dashboard_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TAccountInfo_DashBoardInfo" ALTER COLUMN dashboard_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TAccountInfo_DashBoardInfo_dashboard_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 86542)
-- Name: TAccountInfo_LotteryLog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TAccountInfo_LotteryLog" (
    accountinfo_id integer NOT NULL,
    "account_info_lotteryLog_id" bigint NOT NULL,
    lottery_log_id bigint NOT NULL,
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "deletedAt" timestamp with time zone
);


ALTER TABLE public."TAccountInfo_LotteryLog" OWNER TO postgres;

--
-- TOC entry 5225 (class 0 OID 0)
-- Dependencies: 224
-- Name: COLUMN "TAccountInfo_LotteryLog"."account_info_lotteryLog_id"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."TAccountInfo_LotteryLog"."account_info_lotteryLog_id" IS '主键';


--
-- TOC entry 225 (class 1259 OID 86547)
-- Name: TAccountInfo_LotteryLog_account_info_lotteryLog_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TAccountInfo_LotteryLog" ALTER COLUMN "account_info_lotteryLog_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TAccountInfo_LotteryLog_account_info_lotteryLog_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 86548)
-- Name: TAccountInfo_ReserveLog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TAccountInfo_ReserveLog" (
    pk bigint NOT NULL,
    accountinfo_id bigint,
    reserveinfo_sid bigint,
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "deletedAt" timestamp with time zone
);


ALTER TABLE public."TAccountInfo_ReserveLog" OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 86553)
-- Name: TAccountInfo_ReserveLog_pk_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TAccountInfo_ReserveLog" ALTER COLUMN pk ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TAccountInfo_ReserveLog_pk_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 86554)
-- Name: TAccountInfo_account_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TAccountInfo" ALTER COLUMN account_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TAccountInfo_account_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 86555)
-- Name: TAtariInfo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TAtariInfo" (
    pk bigint NOT NULL,
    accountinfo_id integer,
    atari_dynamic_id character varying(255),
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "deletedAt" timestamp with time zone
);


ALTER TABLE public."TAtariInfo" OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 86560)
-- Name: TAtariInfo_pk_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TAtariInfo" ALTER COLUMN pk ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TAtariInfo_pk_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 264 (class 1259 OID 95998)
-- Name: TBiliLotteryInfoRecord; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TBiliLotteryInfoRecord" (
    pk bigint NOT NULL,
    computed_lottery_pk character varying(100) NOT NULL,
    score integer,
    mid bigint
);


ALTER TABLE public."TBiliLotteryInfoRecord" OWNER TO postgres;

--
-- TOC entry 263 (class 1259 OID 95997)
-- Name: TBiliLotteryInfoRecord_pk_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TBiliLotteryInfoRecord" ALTER COLUMN pk ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."TBiliLotteryInfoRecord_pk_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 86561)
-- Name: TBiliUser; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TBiliUser" (
    mid bigint NOT NULL,
    avatar character varying(255),
    mid_link character varying(255),
    nickname character varying(50),
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "deletedAt" timestamp with time zone
);


ALTER TABLE public."TBiliUser" OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 86568)
-- Name: TBiliUserDetail; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TBiliUserDetail" (
    uid bigint NOT NULL,
    face character varying(255),
    face_nft integer,
    face_nft_new integer,
    name_render json,
    nameplate json,
    official json,
    pendant json,
    " vip" json,
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "deletedAt" timestamp with time zone
);


ALTER TABLE public."TBiliUserDetail" OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 86575)
-- Name: TComment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TComment" (
    mid bigint NOT NULL,
    ctime integer DEFAULT EXTRACT(epoch FROM now()),
    assist integer DEFAULT 0,
    content character varying(4096),
    root bigint,
    parent bigint,
    rcount bigint DEFAULT 0,
    count bigint DEFAULT 0,
    rpid bigint NOT NULL,
    rid bigint NOT NULL,
    "like" bigint DEFAULT 0,
    dislike bigint DEFAULT 0,
    is_reported boolean DEFAULT false,
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "deletedAt" timestamp with time zone,
    is_topped boolean DEFAULT false,
    ip_info_id bigint
);


ALTER TABLE public."TComment" OWNER TO postgres;

--
-- TOC entry 5226 (class 0 OID 0)
-- Dependencies: 233
-- Name: COLUMN "TComment".rcount; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."TComment".rcount IS '二级评论条数';


--
-- TOC entry 5227 (class 0 OID 0)
-- Dependencies: 233
-- Name: COLUMN "TComment".count; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."TComment".count IS '根评论条数';


--
-- TOC entry 5228 (class 0 OID 0)
-- Dependencies: 233
-- Name: COLUMN "TComment".is_reported; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."TComment".is_reported IS '是否被举办';


--
-- TOC entry 234 (class 1259 OID 86592)
-- Name: TCommentInteractRelation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TCommentInteractRelation" (
    pk bigint NOT NULL,
    comment_rpid bigint,
    mid bigint,
    action integer,
    ctime integer DEFAULT EXTRACT(epoch FROM now()),
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "deletedAt" timestamp with time zone,
    ip_info_id bigint
);


ALTER TABLE public."TCommentInteractRelation" OWNER TO postgres;

--
-- TOC entry 5229 (class 0 OID 0)
-- Dependencies: 234
-- Name: COLUMN "TCommentInteractRelation".action; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."TCommentInteractRelation".action IS '需要登录(Cookie 或 APP)
否则恒为 0
0：无
1：已点赞
2：已点踩';


--
-- TOC entry 235 (class 1259 OID 86598)
-- Name: TCommentInteractRelation_pk_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TCommentInteractRelation" ALTER COLUMN pk ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TCommentInteractRelation_pk_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 86599)
-- Name: TCommonLog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TCommonLog" (
    pk integer NOT NULL,
    common_log_account_id integer,
    contents text,
    ts integer,
    func_name text,
    level smallint,
    module_name text,
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "deletedAt" timestamp with time zone
);


ALTER TABLE public."TCommonLog" OWNER TO postgres;

--
-- TOC entry 5230 (class 0 OID 0)
-- Dependencies: 236
-- Name: COLUMN "TCommonLog".level; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."TCommonLog".level IS '从小到大代表严重程度
0为debug（估计用不上
1为info
2为warn
3为error
4为critical';


--
-- TOC entry 237 (class 1259 OID 86606)
-- Name: TCommonLog_pk_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TCommonLog" ALTER COLUMN pk ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TCommonLog_pk_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 86607)
-- Name: TDynamicInfo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TDynamicInfo" (
    dynamic_content character varying(4096),
    up_name character varying(50),
    up_uid character varying(50),
    pubts integer,
    "like" integer,
    comment integer,
    repost integer,
    dynamic_id character varying(255) NOT NULL,
    pk bigint NOT NULL,
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "deletedAt" timestamp with time zone
);


ALTER TABLE public."TDynamicInfo" OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 86614)
-- Name: TDynamicInfo_pk_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TDynamicInfo" ALTER COLUMN pk ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TDynamicInfo_pk_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 86615)
-- Name: TErrorLog_pk_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."TErrorLog_pk_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."TErrorLog_pk_seq" OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 86616)
-- Name: TLiveLotteryLog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TLiveLotteryLog" (
    live_lottery_account_id integer,
    lot_id integer,
    type character varying(32),
    is_succ boolean,
    feedback_info text,
    pk integer NOT NULL,
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "deletedAt" timestamp with time zone
);


ALTER TABLE public."TLiveLotteryLog" OWNER TO postgres;

--
-- TOC entry 5231 (class 0 OID 0)
-- Dependencies: 241
-- Name: COLUMN "TLiveLotteryLog".lot_id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."TLiveLotteryLog".lot_id IS 'B站直播抽奖的id
可能只能到我自己的数据库里面去查询了
当type是goldbox时，lot_id表示金宝箱的id';


--
-- TOC entry 5232 (class 0 OID 0)
-- Dependencies: 241
-- Name: COLUMN "TLiveLotteryLog".type; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."TLiveLotteryLog".type IS 'anchor
redpack
goldbox';


--
-- TOC entry 5233 (class 0 OID 0)
-- Dependencies: 241
-- Name: COLUMN "TLiveLotteryLog".feedback_info; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."TLiveLotteryLog".feedback_info IS '直播抽奖反馈信息，如果成功则为null';


--
-- TOC entry 242 (class 1259 OID 86623)
-- Name: TLiveLotteryLog_pk_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TLiveLotteryLog" ALTER COLUMN pk ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TLiveLotteryLog_pk_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 86624)
-- Name: TLogBiliDailyTask; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TLogBiliDailyTask" (
    pk integer NOT NULL,
    sanlian_ts integer,
    bcoin_ts integer,
    charge_ts integer,
    log_account_id integer NOT NULL,
    live_send_gift_ts integer,
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "deletedAt" timestamp with time zone
);


ALTER TABLE public."TLogBiliDailyTask" OWNER TO postgres;

--
-- TOC entry 5234 (class 0 OID 0)
-- Dependencies: 243
-- Name: COLUMN "TLogBiliDailyTask".sanlian_ts; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."TLogBiliDailyTask".sanlian_ts IS '上一次三连任务的时间戳（秒';


--
-- TOC entry 5235 (class 0 OID 0)
-- Dependencies: 243
-- Name: COLUMN "TLogBiliDailyTask".bcoin_ts; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."TLogBiliDailyTask".bcoin_ts IS '上一次领取b币的时间戳（秒';


--
-- TOC entry 5236 (class 0 OID 0)
-- Dependencies: 243
-- Name: COLUMN "TLogBiliDailyTask".charge_ts; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."TLogBiliDailyTask".charge_ts IS '上一次充电任务的时间戳（秒';


--
-- TOC entry 5237 (class 0 OID 0)
-- Dependencies: 243
-- Name: COLUMN "TLogBiliDailyTask".live_send_gift_ts; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."TLogBiliDailyTask".live_send_gift_ts IS '上一次直播间送免费礼物的时间戳（秒';


--
-- TOC entry 244 (class 1259 OID 86629)
-- Name: TLogBiliDailyTask_pk_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TLogBiliDailyTask" ALTER COLUMN pk ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TLogBiliDailyTask_pk_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 86630)
-- Name: TLotteryLogInfo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TLotteryLogInfo" (
    pk bigint NOT NULL,
    lottery_log text,
    is_success boolean,
    is_manual_reply boolean,
    dynamic_info_id bigint NOT NULL,
    add_ts integer,
    lottery_type integer[],
    update_ts integer,
    comment_msg text,
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "deletedAt" timestamp with time zone
);


ALTER TABLE public."TLotteryLogInfo" OWNER TO postgres;

--
-- TOC entry 5238 (class 0 OID 0)
-- Dependencies: 245
-- Name: COLUMN "TLotteryLogInfo".is_success; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."TLotteryLogInfo".is_success IS '是否抽奖成功了
需要人工判断的
点过赞的动态
404动态
都算成功';


--
-- TOC entry 5239 (class 0 OID 0)
-- Dependencies: 245
-- Name: COLUMN "TLotteryLogInfo".is_manual_reply; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."TLotteryLogInfo".is_manual_reply IS '是否需要人工判断';


--
-- TOC entry 5240 (class 0 OID 0)
-- Dependencies: 245
-- Name: COLUMN "TLotteryLogInfo".lottery_type; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."TLotteryLogInfo".lottery_type IS '抽奖类型 
0：只评论抽奖
1：转发评论抽奖
2：官方抽奖（只转发抽奖）
';


--
-- TOC entry 5241 (class 0 OID 0)
-- Dependencies: 245
-- Name: COLUMN "TLotteryLogInfo".comment_msg; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."TLotteryLogInfo".comment_msg IS '记录评论内容';


--
-- TOC entry 246 (class 1259 OID 86637)
-- Name: TLotteryLogInfo_pk_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TLotteryLogInfo" ALTER COLUMN pk ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TLotteryLogInfo_pk_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 247 (class 1259 OID 86638)
-- Name: TPersonalizedContent; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TPersonalizedContent" (
    oid bigint NOT NULL,
    type integer NOT NULL,
    up_mid bigint,
    ctime integer DEFAULT EXTRACT(epoch FROM now()),
    content_id bigint NOT NULL,
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "deletedAt" timestamp with time zone,
    ip_info_id bigint
);


ALTER TABLE public."TPersonalizedContent" OWNER TO postgres;

--
-- TOC entry 5242 (class 0 OID 0)
-- Dependencies: 247
-- Name: COLUMN "TPersonalizedContent".oid; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."TPersonalizedContent".oid IS '自己的id';


--
-- TOC entry 5243 (class 0 OID 0)
-- Dependencies: 247
-- Name: COLUMN "TPersonalizedContent".type; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."TPersonalizedContent".type IS '1：文字
后续待定';


--
-- TOC entry 5244 (class 0 OID 0)
-- Dependencies: 247
-- Name: COLUMN "TPersonalizedContent".content_id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."TPersonalizedContent".content_id IS '对外显示的业务id';


--
-- TOC entry 248 (class 1259 OID 86644)
-- Name: TPersonalizedContentType1; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TPersonalizedContentType1" (
    rid bigint NOT NULL,
    title character varying(256),
    content character varying(4096),
    "desc" character varying(4096),
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "deletedAt" timestamp with time zone
);


ALTER TABLE public."TPersonalizedContentType1" OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 86651)
-- Name: TPersonalizedContent_oid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."TPersonalizedContent_oid_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."TPersonalizedContent_oid_seq" OWNER TO postgres;

--
-- TOC entry 5245 (class 0 OID 0)
-- Dependencies: 249
-- Name: TPersonalizedContent_oid_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."TPersonalizedContent_oid_seq" OWNED BY public."TPersonalizedContent".oid;


--
-- TOC entry 250 (class 1259 OID 86652)
-- Name: TReserveLotteryInfo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TReserveLotteryInfo" (
    pk bigint NOT NULL,
    reserve_url text,
    etime integer,
    lottery_prize_info text,
    jump_url text,
    reserve_sid bigint NOT NULL,
    available boolean,
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "deletedAt" timestamp with time zone
);


ALTER TABLE public."TReserveLotteryInfo" OWNER TO postgres;

--
-- TOC entry 5246 (class 0 OID 0)
-- Dependencies: 250
-- Name: COLUMN "TReserveLotteryInfo".etime; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."TReserveLotteryInfo".etime IS '时间戳（秒';


--
-- TOC entry 251 (class 1259 OID 86659)
-- Name: TReserveLotteryInfo_pk_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TReserveLotteryInfo" ALTER COLUMN pk ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TReserveLotteryInfo_pk_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 257 (class 1259 OID 87084)
-- Name: TUserActInfoLog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TUserActInfoLog" (
    mid bigint,
    ip character varying(50),
    ua text,
    headers json,
    act_info text,
    pk bigint NOT NULL,
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "deletedAt" timestamp with time zone
);


ALTER TABLE public."TUserActInfoLog" OWNER TO postgres;

--
-- TOC entry 5247 (class 0 OID 0)
-- Dependencies: 257
-- Name: TABLE "TUserActInfoLog"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public."TUserActInfoLog" IS '用户行为日志，记录ip，ua，headers等信息？';


--
-- TOC entry 258 (class 1259 OID 87094)
-- Name: TUserActInfoLog_pk_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TUserActInfoLog" ALTER COLUMN pk ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."TUserActInfoLog_pk_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 252 (class 1259 OID 86660)
-- Name: TUserDetail; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TUserDetail" (
    mid bigint NOT NULL,
    avatar character varying(1024),
    uname character varying(50),
    sign character varying(1024),
    sex character varying(50),
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "deletedAt" timestamp with time zone,
    birthday timestamp with time zone DEFAULT '1970-01-01 00:00:00+08'::timestamp with time zone
);


ALTER TABLE public."TUserDetail" OWNER TO postgres;

--
-- TOC entry 253 (class 1259 OID 86667)
-- Name: TUserInfo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TUserInfo" (
    uid bigint NOT NULL,
    user_name text,
    pwd text,
    role character varying(255) DEFAULT 'level0'::character varying,
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "deletedAt" timestamp with time zone,
    reg_ip_info_id bigint
);


ALTER TABLE public."TUserInfo" OWNER TO postgres;

--
-- TOC entry 5248 (class 0 OID 0)
-- Dependencies: 253
-- Name: COLUMN "TUserInfo".role; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."TUserInfo".role IS 'level0
level1
...
root';


--
-- TOC entry 254 (class 1259 OID 86675)
-- Name: TUserInfo_uid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TUserInfo" ALTER COLUMN uid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TUserInfo_uid_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 255 (class 1259 OID 86676)
-- Name: TUserLevel; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TUserLevel" (
    mid bigint NOT NULL,
    current_exp bigint DEFAULT 0,
    current_level bigint DEFAULT 0,
    current_min bigint DEFAULT 0,
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "deletedAt" timestamp with time zone
);


ALTER TABLE public."TUserLevel" OWNER TO postgres;

--
-- TOC entry 260 (class 1259 OID 87762)
-- Name: TUserNameRecord; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TUserNameRecord" (
    pk bigint NOT NULL,
    mid bigint NOT NULL,
    prev_uname character varying(50),
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "deletedAt" timestamp with time zone
);


ALTER TABLE public."TUserNameRecord" OWNER TO postgres;

--
-- TOC entry 259 (class 1259 OID 87761)
-- Name: TUserNameRecord_pk_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TUserNameRecord" ALTER COLUMN pk ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."TUserNameRecord_pk_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 262 (class 1259 OID 87773)
-- Name: TUserPwdRecord; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TUserPwdRecord" (
    pk bigint NOT NULL,
    mid bigint,
    prev_pwd character varying(255),
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "deletedAt" timestamp with time zone
);


ALTER TABLE public."TUserPwdRecord" OWNER TO postgres;

--
-- TOC entry 261 (class 1259 OID 87772)
-- Name: TUserPwdRecord_pk_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TUserPwdRecord" ALTER COLUMN pk ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."TUserPwdRecord_pk_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 256 (class 1259 OID 86684)
-- Name: TUserVip; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TUserVip" (
    mid bigint NOT NULL,
    vip_due_date integer DEFAULT 0,
    vip_pay_type integer DEFAULT 0,
    vip_status integer DEFAULT 0,
    vip_type integer DEFAULT 0,
    "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "deletedAt" timestamp with time zone
);


ALTER TABLE public."TUserVip" OWNER TO postgres;

--
-- TOC entry 5249 (class 0 OID 0)
-- Dependencies: 256
-- Name: COLUMN "TUserVip".vip_due_date; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."TUserVip".vip_due_date IS 'vip到期时间戳（ms';


--
-- TOC entry 5250 (class 0 OID 0)
-- Dependencies: 256
-- Name: COLUMN "TUserVip".vip_pay_type; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."TUserVip".vip_pay_type IS '大致分成不同充值渠道？';


--
-- TOC entry 5251 (class 0 OID 0)
-- Dependencies: 256
-- Name: COLUMN "TUserVip".vip_status; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."TUserVip".vip_status IS '0：非vip
1：目前就是vip
2：非VIP（充值过，过期了）';


--
-- TOC entry 5252 (class 0 OID 0)
-- Dependencies: 256
-- Name: COLUMN "TUserVip".vip_type; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."TUserVip".vip_type IS '0：非vip
1：月度
2：年度
3：十年
4：百年';


--
-- TOC entry 4915 (class 2604 OID 86693)
-- Name: TPersonalizedContent oid; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TPersonalizedContent" ALTER COLUMN oid SET DEFAULT nextval('public."TPersonalizedContent_oid_seq"'::regclass);


--
-- TOC entry 4947 (class 2606 OID 86802)
-- Name: TAccountBiliAtMsg TAccountBiliAtMsg_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TAccountBiliAtMsg"
    ADD CONSTRAINT "TAccountBiliAtMsg_pkey" PRIMARY KEY (at_id);


--
-- TOC entry 4952 (class 2606 OID 86804)
-- Name: TAccountBiliReplyMsg TAccountBiliReplyMsg_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TAccountBiliReplyMsg"
    ADD CONSTRAINT "TAccountBiliReplyMsg_pkey" PRIMARY KEY (reply_id);


--
-- TOC entry 4950 (class 2606 OID 86806)
-- Name: TAccountBiliWhisperMsg TAccountBiliWhisperMsg_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TAccountBiliWhisperMsg"
    ADD CONSTRAINT "TAccountBiliWhisperMsg_pkey" PRIMARY KEY (msg_key);


--
-- TOC entry 4954 (class 2606 OID 86808)
-- Name: TAccountDetailInfo TAccountDetailInfo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TAccountDetailInfo"
    ADD CONSTRAINT "TAccountDetailInfo_pkey" PRIMARY KEY (account_detail_info_id);


--
-- TOC entry 4958 (class 2606 OID 86810)
-- Name: TAccountInfo_DashBoardInfo TAccountInfo_DashBoardInfo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TAccountInfo_DashBoardInfo"
    ADD CONSTRAINT "TAccountInfo_DashBoardInfo_pkey" PRIMARY KEY (dashboard_id);


--
-- TOC entry 4960 (class 2606 OID 86812)
-- Name: TAccountInfo_LotteryLog TAccountInfo_LotteryLog_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TAccountInfo_LotteryLog"
    ADD CONSTRAINT "TAccountInfo_LotteryLog_pkey" PRIMARY KEY ("account_info_lotteryLog_id");


--
-- TOC entry 4962 (class 2606 OID 86814)
-- Name: TAccountInfo_ReserveLog TAccountInfo_ReserveLog_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TAccountInfo_ReserveLog"
    ADD CONSTRAINT "TAccountInfo_ReserveLog_pkey" PRIMARY KEY (pk);


--
-- TOC entry 4956 (class 2606 OID 86816)
-- Name: TAccountInfo TAccountInfo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TAccountInfo"
    ADD CONSTRAINT "TAccountInfo_pkey" PRIMARY KEY (account_id);


--
-- TOC entry 4964 (class 2606 OID 86818)
-- Name: TAtariInfo TAtariInfo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TAtariInfo"
    ADD CONSTRAINT "TAtariInfo_pkey" PRIMARY KEY (pk);


--
-- TOC entry 5024 (class 2606 OID 96004)
-- Name: TBiliLotteryInfoRecord TBiliLotteryInfoRecord_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TBiliLotteryInfoRecord"
    ADD CONSTRAINT "TBiliLotteryInfoRecord_pkey" PRIMARY KEY (pk);


--
-- TOC entry 4968 (class 2606 OID 86820)
-- Name: TBiliUserDetail TBiliUserDetail_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TBiliUserDetail"
    ADD CONSTRAINT "TBiliUserDetail_pkey" PRIMARY KEY (uid);


--
-- TOC entry 4966 (class 2606 OID 86822)
-- Name: TBiliUser TBiliUser_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TBiliUser"
    ADD CONSTRAINT "TBiliUser_pkey" PRIMARY KEY (mid);


--
-- TOC entry 4973 (class 2606 OID 86824)
-- Name: TCommentInteractRelation TCommentInteractRelation_comment_rpid_mid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TCommentInteractRelation"
    ADD CONSTRAINT "TCommentInteractRelation_comment_rpid_mid_key" UNIQUE (comment_rpid, mid);


--
-- TOC entry 4975 (class 2606 OID 86826)
-- Name: TCommentInteractRelation TCommentInteractRelation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TCommentInteractRelation"
    ADD CONSTRAINT "TCommentInteractRelation_pkey" PRIMARY KEY (pk);


--
-- TOC entry 4970 (class 2606 OID 86828)
-- Name: TComment TComment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TComment"
    ADD CONSTRAINT "TComment_pkey" PRIMARY KEY (rpid);


--
-- TOC entry 4978 (class 2606 OID 86830)
-- Name: TCommonLog TCommonLog_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TCommonLog"
    ADD CONSTRAINT "TCommonLog_pkey" PRIMARY KEY (pk);


--
-- TOC entry 4981 (class 2606 OID 86832)
-- Name: TDynamicInfo TDynamicInfo_dynamic_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TDynamicInfo"
    ADD CONSTRAINT "TDynamicInfo_dynamic_id_key" UNIQUE (dynamic_id);


--
-- TOC entry 4983 (class 2606 OID 86834)
-- Name: TDynamicInfo TDynamicInfo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TDynamicInfo"
    ADD CONSTRAINT "TDynamicInfo_pkey" PRIMARY KEY (pk);


--
-- TOC entry 4986 (class 2606 OID 86836)
-- Name: TLiveLotteryLog TLiveLotteryLog_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TLiveLotteryLog"
    ADD CONSTRAINT "TLiveLotteryLog_pkey" PRIMARY KEY (pk);


--
-- TOC entry 4988 (class 2606 OID 86838)
-- Name: TLogBiliDailyTask TLogBiliDailyTask_log_account_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TLogBiliDailyTask"
    ADD CONSTRAINT "TLogBiliDailyTask_log_account_id_key" UNIQUE (log_account_id);


--
-- TOC entry 4990 (class 2606 OID 86840)
-- Name: TLogBiliDailyTask TLogBiliDailyTask_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TLogBiliDailyTask"
    ADD CONSTRAINT "TLogBiliDailyTask_pkey" PRIMARY KEY (pk);


--
-- TOC entry 4993 (class 2606 OID 86842)
-- Name: TLotteryLogInfo TLotteryLogInfo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TLotteryLogInfo"
    ADD CONSTRAINT "TLotteryLogInfo_pkey" PRIMARY KEY (pk);


--
-- TOC entry 5001 (class 2606 OID 86844)
-- Name: TPersonalizedContentType1 TPersonalizedContentType1_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TPersonalizedContentType1"
    ADD CONSTRAINT "TPersonalizedContentType1_pkey" PRIMARY KEY (rid);


--
-- TOC entry 4995 (class 2606 OID 86846)
-- Name: TPersonalizedContent TPersonalizedContent_oid_type_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TPersonalizedContent"
    ADD CONSTRAINT "TPersonalizedContent_oid_type_key" UNIQUE (oid, type);


--
-- TOC entry 4997 (class 2606 OID 86848)
-- Name: TPersonalizedContent TPersonalizedContent_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TPersonalizedContent"
    ADD CONSTRAINT "TPersonalizedContent_pkey" PRIMARY KEY (content_id);


--
-- TOC entry 5003 (class 2606 OID 86850)
-- Name: TReserveLotteryInfo TReserveLotteryInfo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TReserveLotteryInfo"
    ADD CONSTRAINT "TReserveLotteryInfo_pkey" PRIMARY KEY (pk);


--
-- TOC entry 5005 (class 2606 OID 86852)
-- Name: TReserveLotteryInfo TReserveLotteryInfo_reserve_sid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TReserveLotteryInfo"
    ADD CONSTRAINT "TReserveLotteryInfo_reserve_sid_key" UNIQUE (reserve_sid);


--
-- TOC entry 5018 (class 2606 OID 87101)
-- Name: TUserActInfoLog TUserActInfoLog_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TUserActInfoLog"
    ADD CONSTRAINT "TUserActInfoLog_pkey" PRIMARY KEY (pk);


--
-- TOC entry 5007 (class 2606 OID 86854)
-- Name: TUserDetail TUserDetail_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TUserDetail"
    ADD CONSTRAINT "TUserDetail_pkey" PRIMARY KEY (mid);


--
-- TOC entry 5009 (class 2606 OID 86856)
-- Name: TUserInfo TUserInfo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TUserInfo"
    ADD CONSTRAINT "TUserInfo_pkey" PRIMARY KEY (uid);


--
-- TOC entry 5011 (class 2606 OID 86858)
-- Name: TUserInfo TUserInfo_user_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TUserInfo"
    ADD CONSTRAINT "TUserInfo_user_name_key" UNIQUE (user_name);


--
-- TOC entry 5014 (class 2606 OID 86860)
-- Name: TUserLevel TUserLevel_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TUserLevel"
    ADD CONSTRAINT "TUserLevel_pkey" PRIMARY KEY (mid);


--
-- TOC entry 5020 (class 2606 OID 87788)
-- Name: TUserNameRecord TUserNameRecord_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TUserNameRecord"
    ADD CONSTRAINT "TUserNameRecord_pkey" PRIMARY KEY (pk);


--
-- TOC entry 5022 (class 2606 OID 87790)
-- Name: TUserPwdRecord TUserPwdRecord_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TUserPwdRecord"
    ADD CONSTRAINT "TUserPwdRecord_pkey" PRIMARY KEY (pk);


--
-- TOC entry 5016 (class 2606 OID 86862)
-- Name: TUserVip TUserVip_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TUserVip"
    ADD CONSTRAINT "TUserVip_pkey" PRIMARY KEY (mid);


--
-- TOC entry 5026 (class 2606 OID 96006)
-- Name: TBiliLotteryInfoRecord uq_computed_lottery_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TBiliLotteryInfoRecord"
    ADD CONSTRAINT uq_computed_lottery_pk UNIQUE (computed_lottery_pk);


--
-- TOC entry 4948 (class 1259 OID 86863)
-- Name: TAccountBiliMsg_pkey; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "TAccountBiliMsg_pkey" ON public."TAccountBiliWhisperMsg" USING btree (msg_key);


--
-- TOC entry 4979 (class 1259 OID 86864)
-- Name: TErrorLog_pkey; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "TErrorLog_pkey" ON public."TCommonLog" USING btree (pk);


--
-- TOC entry 5012 (class 1259 OID 86865)
-- Name: UserInfo_pkey; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "UserInfo_pkey" ON public."TUserInfo" USING btree (uid);


--
-- TOC entry 4984 (class 1259 OID 86866)
-- Name: dynamic_id_unique; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX dynamic_id_unique ON public."TDynamicInfo" USING btree (dynamic_id);


--
-- TOC entry 4991 (class 1259 OID 86867)
-- Name: uk-log_account_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "uk-log_account_id" ON public."TLogBiliDailyTask" USING btree (log_account_id);


--
-- TOC entry 4998 (class 1259 OID 86868)
-- Name: uq_content_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX uq_content_id ON public."TPersonalizedContent" USING btree (content_id);


--
-- TOC entry 4999 (class 1259 OID 86869)
-- Name: uq_oid_type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX uq_oid_type ON public."TPersonalizedContent" USING btree (oid, type);


--
-- TOC entry 4971 (class 1259 OID 86870)
-- Name: uq_rpid; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX uq_rpid ON public."TComment" USING btree (rpid);


--
-- TOC entry 4976 (class 1259 OID 86871)
-- Name: uq_rpid_mid; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX uq_rpid_mid ON public."TCommentInteractRelation" USING btree (comment_rpid, mid);


--
-- TOC entry 5067 (class 2606 OID 96007)
-- Name: TBiliLotteryInfoRecord FK_mid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TBiliLotteryInfoRecord"
    ADD CONSTRAINT "FK_mid" FOREIGN KEY (mid) REFERENCES public."TUserInfo"(uid) NOT VALID;


--
-- TOC entry 5027 (class 2606 OID 86872)
-- Name: TAccountBiliAtMsg TAccountBiliAtMsg_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TAccountBiliAtMsg"
    ADD CONSTRAINT "TAccountBiliAtMsg_account_id_fkey" FOREIGN KEY (account_id) REFERENCES public."TAccountInfo"(account_id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- TOC entry 5028 (class 2606 OID 86877)
-- Name: TAccountBiliAtMsg TAccountBiliAtMsg_uid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TAccountBiliAtMsg"
    ADD CONSTRAINT "TAccountBiliAtMsg_uid_fkey" FOREIGN KEY (uid) REFERENCES public."TBiliUser"(mid) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- TOC entry 5032 (class 2606 OID 86882)
-- Name: TAccountBiliReplyMsg TAccountBiliReplyMsg_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TAccountBiliReplyMsg"
    ADD CONSTRAINT "TAccountBiliReplyMsg_account_id_fkey" FOREIGN KEY (account_id) REFERENCES public."TAccountInfo"(account_id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- TOC entry 5033 (class 2606 OID 86887)
-- Name: TAccountBiliReplyMsg TAccountBiliReplyMsg_uid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TAccountBiliReplyMsg"
    ADD CONSTRAINT "TAccountBiliReplyMsg_uid_fkey" FOREIGN KEY (uid) REFERENCES public."TBiliUser"(mid) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- TOC entry 5029 (class 2606 OID 86892)
-- Name: TAccountBiliWhisperMsg TAccountBiliWhisperMsg_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TAccountBiliWhisperMsg"
    ADD CONSTRAINT "TAccountBiliWhisperMsg_account_id_fkey" FOREIGN KEY (account_id) REFERENCES public."TAccountInfo"(account_id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- TOC entry 5030 (class 2606 OID 86897)
-- Name: TAccountBiliWhisperMsg TAccountBiliWhisperMsg_receiver_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TAccountBiliWhisperMsg"
    ADD CONSTRAINT "TAccountBiliWhisperMsg_receiver_id_fkey" FOREIGN KEY (receiver_id) REFERENCES public."TBiliUser"(mid) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- TOC entry 5031 (class 2606 OID 86902)
-- Name: TAccountBiliWhisperMsg TAccountBiliWhisperMsg_sender_uid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TAccountBiliWhisperMsg"
    ADD CONSTRAINT "TAccountBiliWhisperMsg_sender_uid_fkey" FOREIGN KEY (sender_uid) REFERENCES public."TBiliUser"(mid) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- TOC entry 5034 (class 2606 OID 86907)
-- Name: TAccountDetailInfo TAccountDetailInfo_account_info_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TAccountDetailInfo"
    ADD CONSTRAINT "TAccountDetailInfo_account_info_id_fkey" FOREIGN KEY (account_info_id) REFERENCES public."TAccountInfo"(account_id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- TOC entry 5036 (class 2606 OID 86912)
-- Name: TAccountInfo_DashBoardInfo TAccountInfo_DashBoardInfo_accountinfo_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TAccountInfo_DashBoardInfo"
    ADD CONSTRAINT "TAccountInfo_DashBoardInfo_accountinfo_id_fkey" FOREIGN KEY (accountinfo_id) REFERENCES public."TAccountInfo"(account_id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- TOC entry 5037 (class 2606 OID 86917)
-- Name: TAccountInfo_LotteryLog TAccountInfo_LotteryLog_accountinfo_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TAccountInfo_LotteryLog"
    ADD CONSTRAINT "TAccountInfo_LotteryLog_accountinfo_id_fkey" FOREIGN KEY (accountinfo_id) REFERENCES public."TAccountInfo"(account_id) ON UPDATE CASCADE;


--
-- TOC entry 5038 (class 2606 OID 86922)
-- Name: TAccountInfo_LotteryLog TAccountInfo_LotteryLog_lottery_log_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TAccountInfo_LotteryLog"
    ADD CONSTRAINT "TAccountInfo_LotteryLog_lottery_log_id_fkey" FOREIGN KEY (lottery_log_id) REFERENCES public."TLotteryLogInfo"(pk) ON UPDATE CASCADE;


--
-- TOC entry 5039 (class 2606 OID 86927)
-- Name: TAccountInfo_ReserveLog TAccountInfo_ReserveLog_accountinfo_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TAccountInfo_ReserveLog"
    ADD CONSTRAINT "TAccountInfo_ReserveLog_accountinfo_id_fkey" FOREIGN KEY (accountinfo_id) REFERENCES public."TAccountInfo"(account_id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- TOC entry 5040 (class 2606 OID 86932)
-- Name: TAccountInfo_ReserveLog TAccountInfo_ReserveLog_reserveinfo_sid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TAccountInfo_ReserveLog"
    ADD CONSTRAINT "TAccountInfo_ReserveLog_reserveinfo_sid_fkey" FOREIGN KEY (reserveinfo_sid) REFERENCES public."TReserveLotteryInfo"(reserve_sid) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- TOC entry 5035 (class 2606 OID 86937)
-- Name: TAccountInfo TAccountInfo_uid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TAccountInfo"
    ADD CONSTRAINT "TAccountInfo_uid_fkey" FOREIGN KEY (uid) REFERENCES public."TUserInfo"(uid) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- TOC entry 5041 (class 2606 OID 86942)
-- Name: TAtariInfo TAtariInfo_accountinfo_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TAtariInfo"
    ADD CONSTRAINT "TAtariInfo_accountinfo_id_fkey" FOREIGN KEY (accountinfo_id) REFERENCES public."TAccountInfo"(account_id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- TOC entry 5042 (class 2606 OID 86947)
-- Name: TAtariInfo TAtariInfo_atari_dynamic_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TAtariInfo"
    ADD CONSTRAINT "TAtariInfo_atari_dynamic_id_fkey" FOREIGN KEY (atari_dynamic_id) REFERENCES public."TDynamicInfo"(dynamic_id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- TOC entry 5043 (class 2606 OID 86952)
-- Name: TBiliUserDetail TBiliUserDetail_uid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TBiliUserDetail"
    ADD CONSTRAINT "TBiliUserDetail_uid_fkey" FOREIGN KEY (uid) REFERENCES public."TBiliUser"(mid) ON UPDATE CASCADE;


--
-- TOC entry 5050 (class 2606 OID 86957)
-- Name: TCommentInteractRelation TCommentInteractRelation_comment_rpid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TCommentInteractRelation"
    ADD CONSTRAINT "TCommentInteractRelation_comment_rpid_fkey" FOREIGN KEY (comment_rpid) REFERENCES public."TComment"(rpid) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- TOC entry 5051 (class 2606 OID 86962)
-- Name: TCommentInteractRelation TCommentInteractRelation_mid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TCommentInteractRelation"
    ADD CONSTRAINT "TCommentInteractRelation_mid_fkey" FOREIGN KEY (mid) REFERENCES public."TUserInfo"(uid) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- TOC entry 5044 (class 2606 OID 86967)
-- Name: TComment TComment_mid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TComment"
    ADD CONSTRAINT "TComment_mid_fkey" FOREIGN KEY (mid) REFERENCES public."TUserInfo"(uid) ON UPDATE CASCADE;


--
-- TOC entry 5045 (class 2606 OID 87043)
-- Name: TComment TComment_parent_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TComment"
    ADD CONSTRAINT "TComment_parent_fkey" FOREIGN KEY (parent) REFERENCES public."TComment"(rpid) ON DELETE SET NULL NOT VALID;


--
-- TOC entry 5046 (class 2606 OID 86972)
-- Name: TComment TComment_rid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TComment"
    ADD CONSTRAINT "TComment_rid_fkey" FOREIGN KEY (rid) REFERENCES public."TPersonalizedContent"(content_id) ON UPDATE CASCADE;


--
-- TOC entry 5047 (class 2606 OID 87048)
-- Name: TComment TComment_root_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TComment"
    ADD CONSTRAINT "TComment_root_fkey" FOREIGN KEY (root) REFERENCES public."TComment"(rpid) ON DELETE SET NULL NOT VALID;


--
-- TOC entry 5048 (class 2606 OID 87079)
-- Name: TComment TComment_userInfoUid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TComment"
    ADD CONSTRAINT "TComment_userInfoUid_fkey" FOREIGN KEY (mid) REFERENCES public."TUserInfo"(uid) NOT VALID;


--
-- TOC entry 5053 (class 2606 OID 86977)
-- Name: TCommonLog TCommonLog_common_log_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TCommonLog"
    ADD CONSTRAINT "TCommonLog_common_log_account_id_fkey" FOREIGN KEY (common_log_account_id) REFERENCES public."TAccountInfo"(account_id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- TOC entry 5054 (class 2606 OID 86982)
-- Name: TLiveLotteryLog TLiveLotteryLog_live_lottery_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TLiveLotteryLog"
    ADD CONSTRAINT "TLiveLotteryLog_live_lottery_account_id_fkey" FOREIGN KEY (live_lottery_account_id) REFERENCES public."TAccountInfo"(account_id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- TOC entry 5055 (class 2606 OID 86987)
-- Name: TLogBiliDailyTask TLogBiliDailyTask_log_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TLogBiliDailyTask"
    ADD CONSTRAINT "TLogBiliDailyTask_log_account_id_fkey" FOREIGN KEY (log_account_id) REFERENCES public."TAccountInfo"(account_id) ON UPDATE CASCADE;


--
-- TOC entry 5056 (class 2606 OID 86992)
-- Name: TLotteryLogInfo TLotteryLogInfo_dynamic_info_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TLotteryLogInfo"
    ADD CONSTRAINT "TLotteryLogInfo_dynamic_info_id_fkey" FOREIGN KEY (dynamic_info_id) REFERENCES public."TDynamicInfo"(pk) ON UPDATE CASCADE;


--
-- TOC entry 5059 (class 2606 OID 86997)
-- Name: TPersonalizedContentType1 TPersonalizedContentType1_rid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TPersonalizedContentType1"
    ADD CONSTRAINT "TPersonalizedContentType1_rid_fkey" FOREIGN KEY (rid) REFERENCES public."TPersonalizedContent"(content_id) ON UPDATE CASCADE;


--
-- TOC entry 5057 (class 2606 OID 87002)
-- Name: TPersonalizedContent TPersonalizedContent_up_mid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TPersonalizedContent"
    ADD CONSTRAINT "TPersonalizedContent_up_mid_fkey" FOREIGN KEY (up_mid) REFERENCES public."TUserInfo"(uid) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- TOC entry 5064 (class 2606 OID 87125)
-- Name: TUserActInfoLog TUserActInfoLog_mid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TUserActInfoLog"
    ADD CONSTRAINT "TUserActInfoLog_mid_fkey" FOREIGN KEY (mid) REFERENCES public."TUserInfo"(uid) ON DELETE SET NULL NOT VALID;


--
-- TOC entry 5060 (class 2606 OID 87007)
-- Name: TUserDetail TUserDetail_mid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TUserDetail"
    ADD CONSTRAINT "TUserDetail_mid_fkey" FOREIGN KEY (mid) REFERENCES public."TUserInfo"(uid) ON UPDATE CASCADE;


--
-- TOC entry 5062 (class 2606 OID 87012)
-- Name: TUserLevel TUserLevel_mid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TUserLevel"
    ADD CONSTRAINT "TUserLevel_mid_fkey" FOREIGN KEY (mid) REFERENCES public."TUserDetail"(mid) ON UPDATE CASCADE;


--
-- TOC entry 5066 (class 2606 OID 87778)
-- Name: TUserPwdRecord TUserPwdRecord_mid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TUserPwdRecord"
    ADD CONSTRAINT "TUserPwdRecord_mid_fkey" FOREIGN KEY (mid) REFERENCES public."TUserInfo"(uid);


--
-- TOC entry 5063 (class 2606 OID 87017)
-- Name: TUserVip TUserVip_mid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TUserVip"
    ADD CONSTRAINT "TUserVip_mid_fkey" FOREIGN KEY (mid) REFERENCES public."TUserDetail"(mid) ON UPDATE CASCADE;


--
-- TOC entry 5049 (class 2606 OID 87102)
-- Name: TComment ip_info_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TComment"
    ADD CONSTRAINT ip_info_fkey FOREIGN KEY (ip_info_id) REFERENCES public."TUserActInfoLog"(pk) NOT VALID;


--
-- TOC entry 5058 (class 2606 OID 87112)
-- Name: TPersonalizedContent ip_info_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TPersonalizedContent"
    ADD CONSTRAINT ip_info_fkey FOREIGN KEY (ip_info_id) REFERENCES public."TUserActInfoLog"(pk) NOT VALID;


--
-- TOC entry 5052 (class 2606 OID 87716)
-- Name: TCommentInteractRelation ip_info_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TCommentInteractRelation"
    ADD CONSTRAINT ip_info_fkey FOREIGN KEY (ip_info_id) REFERENCES public."TUserActInfoLog"(pk) ON DELETE SET NULL NOT VALID;


--
-- TOC entry 5061 (class 2606 OID 87117)
-- Name: TUserInfo ip_info_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TUserInfo"
    ADD CONSTRAINT ip_info_id_fkey FOREIGN KEY (reg_ip_info_id) REFERENCES public."TUserActInfoLog"(pk) NOT VALID;


--
-- TOC entry 5065 (class 2606 OID 87767)
-- Name: TUserNameRecord uid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TUserNameRecord"
    ADD CONSTRAINT uid FOREIGN KEY (mid) REFERENCES public."TUserInfo"(uid);


-- Completed on 2025-09-08 00:13:20

--
-- PostgreSQL database dump complete
--

