# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bilibili/broadcast/message/ticket/activitygame.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bilibili/broadcast/message/ticket/activitygame.proto',
  package='bilibili.broadcast.message.ticket',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n4bilibili/broadcast/message/ticket/activitygame.proto\x12!bilibili.broadcast.message.ticket\"e\n\tRoomEvent\x12\x42\n\x0broom_status\x18\x01 \x01(\x0e\x32-.bilibili.broadcast.message.ticket.RoomStatus\x12\x14\n\x0croom_message\x18\x02 \x01(\t**\n\nRoomStatus\x12\t\n\x05Pause\x10\x00\x12\x08\n\x04Play\x10\x01\x12\x07\n\x03\x45nd\x10\x02\x62\x06proto3'
)

_ROOMSTATUS = _descriptor.EnumDescriptor(
  name='RoomStatus',
  full_name='bilibili.broadcast.message.ticket.RoomStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Pause', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Play', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='End', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=194,
  serialized_end=236,
)
_sym_db.RegisterEnumDescriptor(_ROOMSTATUS)

RoomStatus = enum_type_wrapper.EnumTypeWrapper(_ROOMSTATUS)
Pause = 0
Play = 1
End = 2



_ROOMEVENT = _descriptor.Descriptor(
  name='RoomEvent',
  full_name='bilibili.broadcast.message.ticket.RoomEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='room_status', full_name='bilibili.broadcast.message.ticket.RoomEvent.room_status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='room_message', full_name='bilibili.broadcast.message.ticket.RoomEvent.room_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=192,
)

_ROOMEVENT.fields_by_name['room_status'].enum_type = _ROOMSTATUS
DESCRIPTOR.message_types_by_name['RoomEvent'] = _ROOMEVENT
DESCRIPTOR.enum_types_by_name['RoomStatus'] = _ROOMSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RoomEvent = _reflection.GeneratedProtocolMessageType('RoomEvent', (_message.Message,), {
  'DESCRIPTOR' : _ROOMEVENT,
  '__module__' : 'bilibili.broadcast.message.ticket.activitygame_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.broadcast.message.ticket.RoomEvent)
  })
_sym_db.RegisterMessage(RoomEvent)


# @@protoc_insertion_point(module_scope)
