# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: bilibili/pangu/gallery/v1/gallery.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import google.protobuf.empty_pb2
import bilibili.pangu.gallery.v1.gallery_pb2


class GalleryInterfaceBase(abc.ABC):

    @abc.abstractmethod
    async def Ping(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, google.protobuf.empty_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def UserInfo(self, stream: 'grpclib.server.Stream[bilibili.pangu.gallery.v1.gallery_pb2.GetUserInfoReq, bilibili.pangu.gallery.v1.gallery_pb2.GetUserInfoReply]') -> None:
        pass

    @abc.abstractmethod
    async def ListNFTByMid(self, stream: 'grpclib.server.Stream[bilibili.pangu.gallery.v1.gallery_pb2.ListNFTByMidReq, bilibili.pangu.gallery.v1.gallery_pb2.ListNFTByMidReply]') -> None:
        pass

    @abc.abstractmethod
    async def ListOrderByMid(self, stream: 'grpclib.server.Stream[bilibili.pangu.gallery.v1.gallery_pb2.ListOrderByMidReq, bilibili.pangu.gallery.v1.gallery_pb2.ListOrderByMidReply]') -> None:
        pass

    @abc.abstractmethod
    async def BasicInfo(self, stream: 'grpclib.server.Stream[bilibili.pangu.gallery.v1.gallery_pb2.BasicInfoReq, bilibili.pangu.gallery.v1.gallery_pb2.BasicInfoReply]') -> None:
        pass

    @abc.abstractmethod
    async def UserCheck(self, stream: 'grpclib.server.Stream[bilibili.pangu.gallery.v1.gallery_pb2.UserCheckReq, bilibili.pangu.gallery.v1.gallery_pb2.UserCheckReply]') -> None:
        pass

    @abc.abstractmethod
    async def AgreePolicy(self, stream: 'grpclib.server.Stream[bilibili.pangu.gallery.v1.gallery_pb2.AgreePolicyReq, bilibili.pangu.gallery.v1.gallery_pb2.AgreePolicyReply]') -> None:
        pass

    @abc.abstractmethod
    async def GetLastPolicy(self, stream: 'grpclib.server.Stream[bilibili.pangu.gallery.v1.gallery_pb2.GetLastPolicyReq, bilibili.pangu.gallery.v1.gallery_pb2.GetLastPolicyReply]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/bilibili.pangu.gallery.v1.GalleryInterface/Ping': grpclib.const.Handler(
                self.Ping,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                google.protobuf.empty_pb2.Empty,
            ),
            '/bilibili.pangu.gallery.v1.GalleryInterface/UserInfo': grpclib.const.Handler(
                self.UserInfo,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.pangu.gallery.v1.gallery_pb2.GetUserInfoReq,
                bilibili.pangu.gallery.v1.gallery_pb2.GetUserInfoReply,
            ),
            '/bilibili.pangu.gallery.v1.GalleryInterface/ListNFTByMid': grpclib.const.Handler(
                self.ListNFTByMid,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.pangu.gallery.v1.gallery_pb2.ListNFTByMidReq,
                bilibili.pangu.gallery.v1.gallery_pb2.ListNFTByMidReply,
            ),
            '/bilibili.pangu.gallery.v1.GalleryInterface/ListOrderByMid': grpclib.const.Handler(
                self.ListOrderByMid,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.pangu.gallery.v1.gallery_pb2.ListOrderByMidReq,
                bilibili.pangu.gallery.v1.gallery_pb2.ListOrderByMidReply,
            ),
            '/bilibili.pangu.gallery.v1.GalleryInterface/BasicInfo': grpclib.const.Handler(
                self.BasicInfo,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.pangu.gallery.v1.gallery_pb2.BasicInfoReq,
                bilibili.pangu.gallery.v1.gallery_pb2.BasicInfoReply,
            ),
            '/bilibili.pangu.gallery.v1.GalleryInterface/UserCheck': grpclib.const.Handler(
                self.UserCheck,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.pangu.gallery.v1.gallery_pb2.UserCheckReq,
                bilibili.pangu.gallery.v1.gallery_pb2.UserCheckReply,
            ),
            '/bilibili.pangu.gallery.v1.GalleryInterface/AgreePolicy': grpclib.const.Handler(
                self.AgreePolicy,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.pangu.gallery.v1.gallery_pb2.AgreePolicyReq,
                bilibili.pangu.gallery.v1.gallery_pb2.AgreePolicyReply,
            ),
            '/bilibili.pangu.gallery.v1.GalleryInterface/GetLastPolicy': grpclib.const.Handler(
                self.GetLastPolicy,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.pangu.gallery.v1.gallery_pb2.GetLastPolicyReq,
                bilibili.pangu.gallery.v1.gallery_pb2.GetLastPolicyReply,
            ),
        }


class GalleryInterfaceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Ping = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.pangu.gallery.v1.GalleryInterface/Ping',
            google.protobuf.empty_pb2.Empty,
            google.protobuf.empty_pb2.Empty,
        )
        self.UserInfo = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.pangu.gallery.v1.GalleryInterface/UserInfo',
            bilibili.pangu.gallery.v1.gallery_pb2.GetUserInfoReq,
            bilibili.pangu.gallery.v1.gallery_pb2.GetUserInfoReply,
        )
        self.ListNFTByMid = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.pangu.gallery.v1.GalleryInterface/ListNFTByMid',
            bilibili.pangu.gallery.v1.gallery_pb2.ListNFTByMidReq,
            bilibili.pangu.gallery.v1.gallery_pb2.ListNFTByMidReply,
        )
        self.ListOrderByMid = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.pangu.gallery.v1.GalleryInterface/ListOrderByMid',
            bilibili.pangu.gallery.v1.gallery_pb2.ListOrderByMidReq,
            bilibili.pangu.gallery.v1.gallery_pb2.ListOrderByMidReply,
        )
        self.BasicInfo = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.pangu.gallery.v1.GalleryInterface/BasicInfo',
            bilibili.pangu.gallery.v1.gallery_pb2.BasicInfoReq,
            bilibili.pangu.gallery.v1.gallery_pb2.BasicInfoReply,
        )
        self.UserCheck = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.pangu.gallery.v1.GalleryInterface/UserCheck',
            bilibili.pangu.gallery.v1.gallery_pb2.UserCheckReq,
            bilibili.pangu.gallery.v1.gallery_pb2.UserCheckReply,
        )
        self.AgreePolicy = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.pangu.gallery.v1.GalleryInterface/AgreePolicy',
            bilibili.pangu.gallery.v1.gallery_pb2.AgreePolicyReq,
            bilibili.pangu.gallery.v1.gallery_pb2.AgreePolicyReply,
        )
        self.GetLastPolicy = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.pangu.gallery.v1.GalleryInterface/GetLastPolicy',
            bilibili.pangu.gallery.v1.gallery_pb2.GetLastPolicyReq,
            bilibili.pangu.gallery.v1.gallery_pb2.GetLastPolicyReply,
        )
