# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: google/protobuf/unittest_no_generic_services.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import google.protobuf.unittest_no_generic_services_pb2


class TestServiceBase(abc.ABC):

    @abc.abstractmethod
    async def Foo(self, stream: 'grpclib.server.Stream[google.protobuf.unittest_no_generic_services_pb2.TestMessage, google.protobuf.unittest_no_generic_services_pb2.TestMessage]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/protobuf_unittest.no_generic_services_test.TestService/Foo': grpclib.const.Handler(
                self.Foo,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.unittest_no_generic_services_pb2.TestMessage,
                google.protobuf.unittest_no_generic_services_pb2.TestMessage,
            ),
        }


class TestServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Foo = grpclib.client.UnaryUnaryMethod(
            channel,
            '/protobuf_unittest.no_generic_services_test.TestService/Foo',
            google.protobuf.unittest_no_generic_services_pb2.TestMessage,
            google.protobuf.unittest_no_generic_services_pb2.TestMessage,
        )
