services:

  nginx:
    container_name: fastapi-biliExplosion-nginx
    image: nginx:latest
    ports:
      - "${NGINX_PORT}:80"
      - "${NGINX_SSL_PORT}:443"
    environment:
      - TZ=${ENV_TZ}
    volumes:
      - ./docker_vol/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./docker_vol/nginx/html:/usr/share/nginx/html
      - ./docker_vol/nginx/logs:/var/log/nginx
      - ./docker_vol/nginx/cert:/etc/nginx/cert
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
  goaccess:
    container_name: fastapi-biliExplosion-goaccess
    environment:
      - LANG=zh_CN.UTF-8
      - TZ=${ENV_TZ}
    build:
      context: ./docker_vol/goaccess
    ports:
      - "7890:7890"
    volumes:
      - ./docker_vol/goaccess/goaccess.conf:/srv/config/goaccess.conf
      - /srv/geodb
      - ${SITE_LOG_DIR}:/srv/logs
      - ${SITE_REPORT_DIR}:/srv/report
      - ${SITE_CERT_DIR}:/srv/certs
    command: [ "--no-global-config", "--config-file=/srv/config/goaccess.conf" ]
    restart: on-failure:3
    extra_hosts:
      - "host.docker.internal:host-gateway"
  standalone:
    container_name: milvus-standalone
    image: docker.1ms.run/milvusdb/milvus:v2.6.2
    command: [ "milvus", "run", "standalone" ]
    security_opt:
      - seccomp:unconfined
    environment:
      - ETCD_USE_EMBED=true
      - ETCD_DATA_DIR=/var/lib/milvus/etcd
      - ETCD_CONFIG_PATH=/milvus/configs/embedEtcd.yaml
      - COMMON_STORAGETYPE=local
      - DEPLOY_MODE=STANDALONE
      - TZ=${ENV_TZ}
    volumes:
      - ./docker_vol/milvus/conf/user.yaml:/milvus/configs/user.yaml
      - ./docker_vol/milvus/conf/embedEtcd.yaml:/milvus/configs/embedEtcd.yaml
      - ./docker_vol/milvus/vol:/var/lib/milvus
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9091/healthz" ]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "9091:9091"
      - "2379:2379"
      - "19530:19530"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
  mysql:
    container_name: fastapi-mysql
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${ENV_TZ}
    volumes:
      - ./docker_vol/mysql_data/data:/var/lib/mysql
      - ./docker_vol/mysql_data/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${MYSQL_PORT}:3306" # 指定宿主机端口与容器端口映射关系，宿主机:容器
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
  redis:
    container_name: fastapi-redis
    image: redis:latest
    environment:
      - TZ=${ENV_TZ}
    volumes:
      - ./docker_vol/redis/data:/data
    ports:
      - "${REDIS_PORT}:6379"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
  rabbitmq:
    container_name: fastapi-rabbitmq
    image: rabbitmq:latest
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_WEBUI_PORT}:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - TZ=${ENV_TZ}
    volumes:
      - ./docker_vol/rabbitmq/data:/var/lib/rabbitmq
      - ./docker_vol/rabbitmq/logs:/var/log/rabbitmq
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
  unidbg:
    container_name: fastapi-unidbg
    image: unidbg-springboot-samsclub
    environment:
      - TZ=${ENV_TZ}
    ports:
      - "${UNIDBG_PORT}:23335"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
  fastapi:
    deploy:
      resources:
        limits:
          memory: 5G
    container_name: fastapi-bili-explosion
    depends_on:
      - mysql
      - redis
      - rabbitmq
      - unidbg
      - lm-studio
    env_file:
      - ./FastapiApp/.env.fastapi.prod
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - PUSHME_TOKEN=${PUSHME_TOKEN}
      - PUSHPLUS_TOKEN=${PUSHPLUS_TOKEN}
      - PROXY_SERVER=${PROXY_SERVER}
      - V2RAY_HOST=${V2RAY_HOST}
      - TZ=${ENV_TZ}
      - SHOW_LOG=${FASTAPI_SHOW_LOG}
    build:
      context: ./FastapiApp
    volumes:
      - ./FastapiApp:/app
      - /app/node_modules  # 保护容器内node_modules
      - ./docker_vol/fastapi/log:/app/scripts/log
    ports:
      - "${FASTAPI_PORT}:23333"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
  postgres:
    container_name: postgres
    image: postgres:alpine3.22
    volumes:
      - ./docker_vol/postgres/data:/var/lib/postgresql
      - ./docker_vol/postgres/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - TZ=${ENV_TZ}
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
  nodejs-pptr: # 生产版本不挂载代码文件，生产环境需要修改代码必须重新build，需要存储的东西都在中间件里面
    container_name: nodejs-pptr
    depends_on:
      - postgres
      - redis
      - fastapi
    build:
      context: ./puppeteer_Bili
      target: prod
    volumes:
      - /app/node_modules  # 保护容器内node_modules
    ports:
      - "${NODEJS_PPTR_PORT}:9923"
    restart: unless-stopped
    environment:
      - DB=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/PPTR_Bili_Lot
      - DEV_DB=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/DEV_PPTR_Bili_Lot
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PWD=
      - FASTAPI_URI=http://fastapi-bili-explosion:23333
      - FASTAPI_DEV_URI=http://fastapi-bili-explosion:23333
      - FASTAPI_RPA_URI=http://fastapi-rpa:8080
      - FASTAPI_RPA_DEV_URI=http://fastapi-rpa:8000
      - TZ=${ENV_TZ}
    extra_hosts:
      - "host.docker.internal:host-gateway"
  nodejs-pptr-dev:
    container_name: nodejs-pptr-dev
    depends_on:
      - postgres
      - redis
    build:
      context: ./puppeteer_Bili
      target: dev
    ports:
      - "${NODEJS_PPTR_PORT}:9926"
    volumes:
      - ./puppeteer_Bili:/app
      - ./docker_vol/pptr/dev/npm_logs:/root/.npm/_logs
      - /app/node_modules  # 保护容器内node_modules
    environment:
      - DB=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/PPTR_Bili_Lot
      - DEV_DB=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/DEV_PPTR_Bili_Lot
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PWD=
      - FASTAPI_URI=http://fastapi-bili-explosion:23333
      - FASTAPI_DEV_URI=http://fastapi-bili-explosion:23333
      - FASTAPI_RPA_URI=http://fastapi-rpa:8080
      - FASTAPI_RPA_DEV_URI=http://fastapi-rpa:8000
      - TZ=${ENV_TZ}
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
  lm-studio:
    container_name: fastapi-lm-studio
    build:
      context: ./docker_vol/lm_studio
    mem_limit: 512m
    volumes:
      - /root/.lmstudio/models
    ports:
      - ${LMSTUDIO_PORT}:1234
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
  go-proxy-ipv6-server:
    container_name: go-proxy-ipv6-server
    build:
      context: ./go-proxy-ipv6-pool-auto
    ports:
      - "3128:3128"
    networks:
      - my-network
    environment:
      - NET_IF=eth0
      -
networks:
  default:
    enable_ipv6: true
    name: fastapi
    driver: bridge
  ipv6-proxy-server-network:
    enable_ipv6: true
    driver: bridge
    ipam:
      config:
        - subnet: "2409:8a1e:2e90:d20::/64"