# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bilibili/app/distribution/setting/privacy.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bilibili.app.distribution.v1 import distribution_pb2 as bilibili_dot_app_dot_distribution_dot_v1_dot_distribution__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bilibili/app/distribution/setting/privacy.proto',
  package='bilibili.app.distribution.setting.privacy',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n/bilibili/app/distribution/setting/privacy.proto\x12)bilibili.app.distribution.setting.privacy\x1a/bilibili/app/distribution/v1/distribution.proto\"_\n\x18MidPrivacySettingsConfig\x12\x43\n\x12recommend_to_known\x18\x01 \x01(\x0b\x32\'.bilibili.app.distribution.v1.BoolValue\"\x9c\x01\n\x15PrivacySettingsConfig\x12\x43\n\x12\x61\x64_recommand_store\x18\x01 \x01(\x0b\x32\'.bilibili.app.distribution.v1.BoolValue\x12>\n\rsensor_access\x18\x02 \x01(\x0b\x32\'.bilibili.app.distribution.v1.BoolValueb\x06proto3'
  ,
  dependencies=[bilibili_dot_app_dot_distribution_dot_v1_dot_distribution__pb2.DESCRIPTOR,])




_MIDPRIVACYSETTINGSCONFIG = _descriptor.Descriptor(
  name='MidPrivacySettingsConfig',
  full_name='bilibili.app.distribution.setting.privacy.MidPrivacySettingsConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='recommend_to_known', full_name='bilibili.app.distribution.setting.privacy.MidPrivacySettingsConfig.recommend_to_known', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=238,
)


_PRIVACYSETTINGSCONFIG = _descriptor.Descriptor(
  name='PrivacySettingsConfig',
  full_name='bilibili.app.distribution.setting.privacy.PrivacySettingsConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ad_recommand_store', full_name='bilibili.app.distribution.setting.privacy.PrivacySettingsConfig.ad_recommand_store', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sensor_access', full_name='bilibili.app.distribution.setting.privacy.PrivacySettingsConfig.sensor_access', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=397,
)

_MIDPRIVACYSETTINGSCONFIG.fields_by_name['recommend_to_known'].message_type = bilibili_dot_app_dot_distribution_dot_v1_dot_distribution__pb2._BOOLVALUE
_PRIVACYSETTINGSCONFIG.fields_by_name['ad_recommand_store'].message_type = bilibili_dot_app_dot_distribution_dot_v1_dot_distribution__pb2._BOOLVALUE
_PRIVACYSETTINGSCONFIG.fields_by_name['sensor_access'].message_type = bilibili_dot_app_dot_distribution_dot_v1_dot_distribution__pb2._BOOLVALUE
DESCRIPTOR.message_types_by_name['MidPrivacySettingsConfig'] = _MIDPRIVACYSETTINGSCONFIG
DESCRIPTOR.message_types_by_name['PrivacySettingsConfig'] = _PRIVACYSETTINGSCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MidPrivacySettingsConfig = _reflection.GeneratedProtocolMessageType('MidPrivacySettingsConfig', (_message.Message,), {
  'DESCRIPTOR' : _MIDPRIVACYSETTINGSCONFIG,
  '__module__' : 'bilibili.app.distribution.setting.privacy_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.app.distribution.setting.privacy.MidPrivacySettingsConfig)
  })
_sym_db.RegisterMessage(MidPrivacySettingsConfig)

PrivacySettingsConfig = _reflection.GeneratedProtocolMessageType('PrivacySettingsConfig', (_message.Message,), {
  'DESCRIPTOR' : _PRIVACYSETTINGSCONFIG,
  '__module__' : 'bilibili.app.distribution.setting.privacy_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.app.distribution.setting.privacy.PrivacySettingsConfig)
  })
_sym_db.RegisterMessage(PrivacySettingsConfig)


# @@protoc_insertion_point(module_scope)
