# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: bilibili/app/show/popular/v1/popular.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import bilibili.app.card.v1.card_pb2
import bilibili.app.archive.middleware.v1.preload_pb2
import bilibili.app.show.popular.v1.popular_pb2


class PopularBase(abc.ABC):

    @abc.abstractmethod
    async def Index(self, stream: 'grpclib.server.Stream[bilibili.app.show.popular.v1.popular_pb2.PopularResultReq, bilibili.app.show.popular.v1.popular_pb2.PopularReply]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/bilibili.app.show.v1.Popular/Index': grpclib.const.Handler(
                self.Index,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.show.popular.v1.popular_pb2.PopularResultReq,
                bilibili.app.show.popular.v1.popular_pb2.PopularReply,
            ),
        }


class PopularStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Index = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.show.v1.Popular/Index',
            bilibili.app.show.popular.v1.popular_pb2.PopularResultReq,
            bilibili.app.show.popular.v1.popular_pb2.PopularReply,
        )
