# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bilibili/broadcast/v1/laser.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bilibili/broadcast/v1/laser.proto',
  package='bilibili.broadcast.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!bilibili/broadcast/v1/laser.proto\x12\x15\x62ilibili.broadcast.v1\x1a\x1bgoogle/protobuf/empty.proto\"2\n\x12LaserLogUploadResp\x12\x0e\n\x06taskid\x18\x01 \x01(\x03\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t2c\n\x05Laser\x12Z\n\x13WatchLogUploadEvent\x12\x16.google.protobuf.Empty\x1a).bilibili.broadcast.v1.LaserLogUploadResp0\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_LASERLOGUPLOADRESP = _descriptor.Descriptor(
  name='LaserLogUploadResp',
  full_name='bilibili.broadcast.v1.LaserLogUploadResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='taskid', full_name='bilibili.broadcast.v1.LaserLogUploadResp.taskid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date', full_name='bilibili.broadcast.v1.LaserLogUploadResp.date', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=139,
)

DESCRIPTOR.message_types_by_name['LaserLogUploadResp'] = _LASERLOGUPLOADRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LaserLogUploadResp = _reflection.GeneratedProtocolMessageType('LaserLogUploadResp', (_message.Message,), {
  'DESCRIPTOR' : _LASERLOGUPLOADRESP,
  '__module__' : 'bilibili.broadcast.v1.laser_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.broadcast.v1.LaserLogUploadResp)
  })
_sym_db.RegisterMessage(LaserLogUploadResp)



_LASER = _descriptor.ServiceDescriptor(
  name='Laser',
  full_name='bilibili.broadcast.v1.Laser',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=141,
  serialized_end=240,
  methods=[
  _descriptor.MethodDescriptor(
    name='WatchLogUploadEvent',
    full_name='bilibili.broadcast.v1.Laser.WatchLogUploadEvent',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_LASERLOGUPLOADRESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LASER)

DESCRIPTOR.services_by_name['Laser'] = _LASER

# @@protoc_insertion_point(module_scope)
