# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: bilibili/broadcast/message/editor/notify.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import google.protobuf.empty_pb2
import bilibili.broadcast.message.editor.notify_pb2


class OperationNotifyBase(abc.ABC):

    @abc.abstractmethod
    async def OperationNotify(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, bilibili.broadcast.message.editor.notify_pb2.Notify]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/bilibili.broadcast.message.editor.OperationNotify/OperationNotify': grpclib.const.Handler(
                self.OperationNotify,
                grpclib.const.Cardinality.UNARY_STREAM,
                google.protobuf.empty_pb2.Empty,
                bilibili.broadcast.message.editor.notify_pb2.Notify,
            ),
        }


class OperationNotifyStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.OperationNotify = grpclib.client.UnaryStreamMethod(
            channel,
            '/bilibili.broadcast.message.editor.OperationNotify/OperationNotify',
            google.protobuf.empty_pb2.Empty,
            bilibili.broadcast.message.editor.notify_pb2.Notify,
        )
