# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bilibili/broadcast/message/fission/notify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bilibili/broadcast/message/fission/notify.proto',
  package='bilibili.broadcast.message.fission',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n/bilibili/broadcast/message/fission/notify.proto\x12\"bilibili.broadcast.message.fission\x1a\x1bgoogle/protobuf/empty.proto\"-\n\x0fGameNotifyReply\x12\x0c\n\x04type\x18\x01 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t2f\n\x07\x46ission\x12[\n\nGameNotify\x12\x16.google.protobuf.Empty\x1a\x33.bilibili.broadcast.message.fission.GameNotifyReply0\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_GAMENOTIFYREPLY = _descriptor.Descriptor(
  name='GameNotifyReply',
  full_name='bilibili.broadcast.message.fission.GameNotifyReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='bilibili.broadcast.message.fission.GameNotifyReply.type', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='bilibili.broadcast.message.fission.GameNotifyReply.data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=161,
)

DESCRIPTOR.message_types_by_name['GameNotifyReply'] = _GAMENOTIFYREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GameNotifyReply = _reflection.GeneratedProtocolMessageType('GameNotifyReply', (_message.Message,), {
  'DESCRIPTOR' : _GAMENOTIFYREPLY,
  '__module__' : 'bilibili.broadcast.message.fission.notify_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.broadcast.message.fission.GameNotifyReply)
  })
_sym_db.RegisterMessage(GameNotifyReply)



_FISSION = _descriptor.ServiceDescriptor(
  name='Fission',
  full_name='bilibili.broadcast.message.fission.Fission',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=163,
  serialized_end=265,
  methods=[
  _descriptor.MethodDescriptor(
    name='GameNotify',
    full_name='bilibili.broadcast.message.fission.Fission.GameNotify',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_GAMENOTIFYREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FISSION)

DESCRIPTOR.services_by_name['Fission'] = _FISSION

# @@protoc_insertion_point(module_scope)
