# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bilibili/app/playeronline/v1/playeronline.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bilibili/app/playeronline/v1/playeronline.proto',
  package='bilibili.app.playeronline.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n/bilibili/app/playeronline/v1/playeronline.proto\x12\x1c\x62ilibili.app.playeronline.v1\"\t\n\x07NoReply\"\xa3\x01\n\x11PlayerOnlineReply\x12\x12\n\ntotal_text\x18\x01 \x01(\t\x12\x10\n\x08sec_next\x18\x02 \x01(\x03\x12\x13\n\x0b\x62ottom_show\x18\x03 \x01(\x08\x12\x10\n\x08sdm_show\x18\x04 \x01(\x08\x12\x10\n\x08sdm_text\x18\x05 \x01(\t\x12\x14\n\x0ctotal_number\x18\x06 \x01(\x03\x12\x19\n\x11total_number_text\x18\x07 \x01(\t\">\n\x0fPlayerOnlineReq\x12\x0b\n\x03\x61id\x18\x01 \x01(\x03\x12\x0b\n\x03\x63id\x18\x02 \x01(\x03\x12\x11\n\tplay_open\x18\x03 \x01(\x08\"Y\n\x11PremiereInfoReply\x12\x1a\n\x12premiere_over_text\x18\x01 \x01(\t\x12\x13\n\x0bparticipant\x18\x02 \x01(\x03\x12\x13\n\x0binteraction\x18\x03 \x01(\x03\"\x1e\n\x0fPremiereInfoReq\x12\x0b\n\x03\x61id\x18\x01 \x01(\x03\"9\n\x0eReportWatchReq\x12\x0b\n\x03\x61id\x18\x01 \x01(\x03\x12\x0b\n\x03\x62iz\x18\x02 \x01(\t\x12\r\n\x05\x62uvid\x18\x03 \x01(\t2\xd2\x02\n\x0cPlayerOnline\x12n\n\x0cPlayerOnline\x12-.bilibili.app.playeronline.v1.PlayerOnlineReq\x1a/.bilibili.app.playeronline.v1.PlayerOnlineReply\x12n\n\x0cPremiereInfo\x12-.bilibili.app.playeronline.v1.PremiereInfoReq\x1a/.bilibili.app.playeronline.v1.PremiereInfoReply\x12\x62\n\x0bReportWatch\x12,.bilibili.app.playeronline.v1.ReportWatchReq\x1a%.bilibili.app.playeronline.v1.NoReplyb\x06proto3'
)




_NOREPLY = _descriptor.Descriptor(
  name='NoReply',
  full_name='bilibili.app.playeronline.v1.NoReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=90,
)


_PLAYERONLINEREPLY = _descriptor.Descriptor(
  name='PlayerOnlineReply',
  full_name='bilibili.app.playeronline.v1.PlayerOnlineReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='total_text', full_name='bilibili.app.playeronline.v1.PlayerOnlineReply.total_text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sec_next', full_name='bilibili.app.playeronline.v1.PlayerOnlineReply.sec_next', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bottom_show', full_name='bilibili.app.playeronline.v1.PlayerOnlineReply.bottom_show', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sdm_show', full_name='bilibili.app.playeronline.v1.PlayerOnlineReply.sdm_show', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sdm_text', full_name='bilibili.app.playeronline.v1.PlayerOnlineReply.sdm_text', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_number', full_name='bilibili.app.playeronline.v1.PlayerOnlineReply.total_number', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_number_text', full_name='bilibili.app.playeronline.v1.PlayerOnlineReply.total_number_text', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=256,
)


_PLAYERONLINEREQ = _descriptor.Descriptor(
  name='PlayerOnlineReq',
  full_name='bilibili.app.playeronline.v1.PlayerOnlineReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='aid', full_name='bilibili.app.playeronline.v1.PlayerOnlineReq.aid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cid', full_name='bilibili.app.playeronline.v1.PlayerOnlineReq.cid', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='play_open', full_name='bilibili.app.playeronline.v1.PlayerOnlineReq.play_open', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=320,
)


_PREMIEREINFOREPLY = _descriptor.Descriptor(
  name='PremiereInfoReply',
  full_name='bilibili.app.playeronline.v1.PremiereInfoReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='premiere_over_text', full_name='bilibili.app.playeronline.v1.PremiereInfoReply.premiere_over_text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='participant', full_name='bilibili.app.playeronline.v1.PremiereInfoReply.participant', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='interaction', full_name='bilibili.app.playeronline.v1.PremiereInfoReply.interaction', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=322,
  serialized_end=411,
)


_PREMIEREINFOREQ = _descriptor.Descriptor(
  name='PremiereInfoReq',
  full_name='bilibili.app.playeronline.v1.PremiereInfoReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='aid', full_name='bilibili.app.playeronline.v1.PremiereInfoReq.aid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=413,
  serialized_end=443,
)


_REPORTWATCHREQ = _descriptor.Descriptor(
  name='ReportWatchReq',
  full_name='bilibili.app.playeronline.v1.ReportWatchReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='aid', full_name='bilibili.app.playeronline.v1.ReportWatchReq.aid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='biz', full_name='bilibili.app.playeronline.v1.ReportWatchReq.biz', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='buvid', full_name='bilibili.app.playeronline.v1.ReportWatchReq.buvid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=445,
  serialized_end=502,
)

DESCRIPTOR.message_types_by_name['NoReply'] = _NOREPLY
DESCRIPTOR.message_types_by_name['PlayerOnlineReply'] = _PLAYERONLINEREPLY
DESCRIPTOR.message_types_by_name['PlayerOnlineReq'] = _PLAYERONLINEREQ
DESCRIPTOR.message_types_by_name['PremiereInfoReply'] = _PREMIEREINFOREPLY
DESCRIPTOR.message_types_by_name['PremiereInfoReq'] = _PREMIEREINFOREQ
DESCRIPTOR.message_types_by_name['ReportWatchReq'] = _REPORTWATCHREQ
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NoReply = _reflection.GeneratedProtocolMessageType('NoReply', (_message.Message,), {
  'DESCRIPTOR' : _NOREPLY,
  '__module__' : 'bilibili.app.playeronline.v1.playeronline_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.app.playeronline.v1.NoReply)
  })
_sym_db.RegisterMessage(NoReply)

PlayerOnlineReply = _reflection.GeneratedProtocolMessageType('PlayerOnlineReply', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERONLINEREPLY,
  '__module__' : 'bilibili.app.playeronline.v1.playeronline_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.app.playeronline.v1.PlayerOnlineReply)
  })
_sym_db.RegisterMessage(PlayerOnlineReply)

PlayerOnlineReq = _reflection.GeneratedProtocolMessageType('PlayerOnlineReq', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERONLINEREQ,
  '__module__' : 'bilibili.app.playeronline.v1.playeronline_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.app.playeronline.v1.PlayerOnlineReq)
  })
_sym_db.RegisterMessage(PlayerOnlineReq)

PremiereInfoReply = _reflection.GeneratedProtocolMessageType('PremiereInfoReply', (_message.Message,), {
  'DESCRIPTOR' : _PREMIEREINFOREPLY,
  '__module__' : 'bilibili.app.playeronline.v1.playeronline_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.app.playeronline.v1.PremiereInfoReply)
  })
_sym_db.RegisterMessage(PremiereInfoReply)

PremiereInfoReq = _reflection.GeneratedProtocolMessageType('PremiereInfoReq', (_message.Message,), {
  'DESCRIPTOR' : _PREMIEREINFOREQ,
  '__module__' : 'bilibili.app.playeronline.v1.playeronline_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.app.playeronline.v1.PremiereInfoReq)
  })
_sym_db.RegisterMessage(PremiereInfoReq)

ReportWatchReq = _reflection.GeneratedProtocolMessageType('ReportWatchReq', (_message.Message,), {
  'DESCRIPTOR' : _REPORTWATCHREQ,
  '__module__' : 'bilibili.app.playeronline.v1.playeronline_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.app.playeronline.v1.ReportWatchReq)
  })
_sym_db.RegisterMessage(ReportWatchReq)



_PLAYERONLINE = _descriptor.ServiceDescriptor(
  name='PlayerOnline',
  full_name='bilibili.app.playeronline.v1.PlayerOnline',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=505,
  serialized_end=843,
  methods=[
  _descriptor.MethodDescriptor(
    name='PlayerOnline',
    full_name='bilibili.app.playeronline.v1.PlayerOnline.PlayerOnline',
    index=0,
    containing_service=None,
    input_type=_PLAYERONLINEREQ,
    output_type=_PLAYERONLINEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PremiereInfo',
    full_name='bilibili.app.playeronline.v1.PlayerOnline.PremiereInfo',
    index=1,
    containing_service=None,
    input_type=_PREMIEREINFOREQ,
    output_type=_PREMIEREINFOREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ReportWatch',
    full_name='bilibili.app.playeronline.v1.PlayerOnline.ReportWatch',
    index=2,
    containing_service=None,
    input_type=_REPORTWATCHREQ,
    output_type=_NOREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PLAYERONLINE)

DESCRIPTOR.services_by_name['PlayerOnline'] = _PLAYERONLINE

# @@protoc_insertion_point(module_scope)
