"""models: 公共响应码、响应消息、响应模型与认证模型（统一使用 sqlmodel）"""

# 必须在导入子模块之前暴露 IntEnumAutoDoc / StrEnumAutoDoc：
# 子模块（response_code / interaction / report / response_msg / rpc ...）会
# `from bili_common.models import IntEnumAutoDoc` / `StrEnumAutoDoc`，
# 若放在子模块导入之后会因 models 包尚未完成初始化而触发 circular import。
from bili_common.core.enums import IntEnumAutoDoc, StrEnumAutoDoc

from bili_common.models.response_code import ResponseCode
from bili_common.models.response_msg import ResponseMsg
from bili_common.models.response import (
    StandardResponse,
    success_response,
    error_response,
    custom_response,
)
from bili_common.models.depends import (
    AuthInfo,
    BrowserReqInfo,
    BrowserReqAuthInfo,
    VerifyBrowserDependsReq,
    VerifyPluginDependsReq,
    BrowserPluginReqInfo,
)
from bili_common.models.pagination import (
    ResponsePaginationItems,
    RequestPaginationParams,
    RequestCursorParams,
    RequestOffsetLimitParams,
)
from bili_common.models.lottery_query import (
    LotteryDataSortEnum,
    SortOrderEnum,
    OthersLotDynSortEnum,
    OthersLotDynSortOrderEnum,
    TimePresetEnum,
    LotteryStatusEnum,
    LotteryPaginationParams,
    LotterySearchPaginationParams,
    LotteryAdvancedQueryParams,
    OthersLotDynListFilterMetadata,
)
from bili_common.models.rpc import (
    RpcMethodName,
    ROUTING_KEY_PREFIX,
    ALLOWED_RPC_METHODS,
    routing_key_for,
    validate_rpc_method,
    get_allowed_method_names,
    RpcMethodInfo,
    RpcMethodInfoResponse,
    build_method_responses,
)
from bili_common.models.rpc_params import (
    BaseLotteryRpcParams,
    GetReserveLotteryRpcParams,
    GetOfficialLotteryRpcParams,
    GetChargeLotteryRpcParams,
    GetTopicLotteryRpcParams,
    GetAllLotteryRpcParams,
    GetOthersLotDynListRpcParams,
    RPC_METHOD_PARAMS_MODEL_MAP,
    RPC_METHOD_PARAMS_FIELD_MAP,
)
# 内部校验契约（be-message 客户端 → be-bilibili-crawler，2.20.0）
from bili_common.rpc.lottery import (
    CheckLotteryExistRpcParams,
    CheckLotteryExistRpcResult,
    LotteryDetailItem,
)
from bili_common.models.user_search import (
    UserSearchParams,
    PptrUserRoleInfo,
    PptrUserLevelInfo,
    PptrUserVipInfo,
    PptrUserSearchItem,
    PptrUserSearchResult,
)
from bili_common.models.pptr_user_gateway import (
    PptrUserNavData,
    PptrUserInfoUpdateParams,
    PptrUserInfoUpdateResult,
    PptrUserRoleSetParams,
    PptrUserRoleSetResult,
    VALID_SEX_VALUES,
    VALID_ROLES,
    ROLE_ROOT,
)
from bili_common.models.pptr_user_rpc import (
    pptr_routing_key_for,
    PptrGetUserInfoParams,
    PptrGetUserCardParams,
    PptrCreateUserParams,
    PptrUpdateUserInfoParams,
    PptrGetUserLevelParams,
    PptrSetUserLevelParams,
    PptrSetUserDetailParams,
    PptrSetUserRoleParams,
    PptrUserCard,
    PptrUserProfile,
    PptrCreateUserResult,
    PptrUpdateUserInfoResult,
    PptrUserLevelInfo,
    PptrSetResult,
    PptrAddExpParams,
    PptrAddExpResult,
    PptrAddDailyLoginExpParams,
    PptrAddDailyLoginExpResult,
    PptrAddUsernameRecordParams,
    PptrAddUsernameRecordResult,
    PptrGetUserNavParams,
    PPTR_USER_RPC_CONTRACT,
)
from bili_common.models.push import (
    PushChannelConfig,
    PushMessagePayload,
)
from bili_common.models.push_rpc import (
    PUSH_RPC_CONTRACT,
    PUSH_RPC_ROUTING_KEY_PREFIX,
    PushRpcMethodName,
    PushRpcSendNowParams,
    PushRpcSendNowResult,
    PushRpcSendParams,
    PushRpcSendResult,
    push_rpc_routing_key_for,
)
from bili_common.models.notify_rpc import (
    NOTIFY_RPC_CONTRACT,
    NOTIFY_RPC_ROUTING_KEY_PREFIX,
    NotifyRpcMethodName,
    NotifyLevelEnum,
    NotifyTargetTypeEnum,
    PublishNotifyParams,
    PublishNotifyResult,
    notify_rpc_routing_key_for,
)
from bili_common.models.admin_status import AdminStatusResponse
from bili_common.models.interaction import InteractionBizTypeEnum
from bili_common.models.interaction_stat import InteractionStatBase

from bili_common.models.auto_str import AutoStrMixin, SnowflakeInt


__all__ = [
    "ResponseCode",
    "ResponseMsg",
    "StandardResponse",
    "success_response",
    "error_response",
    "custom_response",
    "AuthInfo",
    "BrowserReqInfo",
    "BrowserReqAuthInfo",
    "VerifyBrowserDependsReq",
    "VerifyPluginDependsReq",
    "BrowserPluginReqInfo",
    "ResponsePaginationItems",
    "RequestPaginationParams",
    "RequestCursorParams",
    "RequestOffsetLimitParams",
    "LotteryDataSortEnum",
    "SortOrderEnum",
    "OthersLotDynSortEnum",
    "OthersLotDynSortOrderEnum",
    "TimePresetEnum",
    "LotteryStatusEnum",
    "LotteryPaginationParams",
    "LotterySearchPaginationParams",
    "LotteryAdvancedQueryParams",
    "OthersLotDynListFilterMetadata",
    "RpcMethodName",
    "ROUTING_KEY_PREFIX",
    "ALLOWED_RPC_METHODS",
    "routing_key_for",
    "validate_rpc_method",
    "get_allowed_method_names",
    "RpcMethodInfo",
    "RpcMethodInfoResponse",
    "build_method_responses",
    "BaseLotteryRpcParams",
    "GetReserveLotteryRpcParams",
    "GetOfficialLotteryRpcParams",
    "GetChargeLotteryRpcParams",
    "GetTopicLotteryRpcParams",
    "GetAllLotteryRpcParams",
    "GetOthersLotDynListRpcParams",
    "RPC_METHOD_PARAMS_MODEL_MAP",
    "RPC_METHOD_PARAMS_FIELD_MAP",
    "CheckLotteryExistRpcParams",
    "CheckLotteryExistRpcResult",
    "LotteryDetailItem",
    "UserSearchParams",
    "PptrUserRoleInfo",
    "PptrUserLevelInfo",
    "PptrUserVipInfo",
    "PptrUserSearchItem",
    "PptrUserSearchResult",
    "PptrUserNavData",
    "PptrUserInfoUpdateParams",
    "PptrUserInfoUpdateResult",
    "PptrUserRoleSetParams",
    "PptrUserRoleSetResult",
    "VALID_SEX_VALUES",
    "VALID_ROLES",
    "ROLE_ROOT",
    "pptr_routing_key_for",
    "PptrGetUserInfoParams",
    "PptrGetUserCardParams",
    "PptrCreateUserParams",
    "PptrUpdateUserInfoParams",
    "PptrGetUserLevelParams",
    "PptrSetUserLevelParams",
    "PptrSetUserDetailParams",
    "PptrSetUserRoleParams",
    "PptrUserCard",
    "PptrUserProfile",
    "PptrCreateUserResult",
    "PptrUpdateUserInfoResult",
    "PptrUserLevelInfo",
    "PptrSetResult",
    "PptrAddExpParams",
    "PptrAddExpResult",
    "PptrAddDailyLoginExpParams",
    "PptrAddDailyLoginExpResult",
    "PptrAddUsernameRecordParams",
    "PptrAddUsernameRecordResult",
    "PptrGetUserNavParams",
    "PPTR_USER_RPC_CONTRACT",
    "PUSH_RPC_CONTRACT",
    "PUSH_RPC_ROUTING_KEY_PREFIX",
    "PushChannelConfig",
    "PushMessagePayload",
    "PushRpcMethodName",
    "PushRpcSendNowParams",
    "PushRpcSendNowResult",
    "PushRpcSendParams",
    "PushRpcSendResult",
    "push_rpc_routing_key_for",
    "NOTIFY_RPC_CONTRACT",
    "NOTIFY_RPC_ROUTING_KEY_PREFIX",
    "NotifyRpcMethodName",
    "NotifyLevelEnum",
    "NotifyTargetTypeEnum",
    "PublishNotifyParams",
    "PublishNotifyResult",
    "notify_rpc_routing_key_for",
    "AdminStatusResponse",
    # 社区互动（2.18.0）
    "InteractionBizTypeEnum",
    "InteractionStatBase",
    # 通用 IntEnum / StrEnum 基类（自动生成 OpenAPI 枚举选项文档）
    "IntEnumAutoDoc",
    "StrEnumAutoDoc",
    "AutoStrMixin",
    "SnowflakeInt",
]
