"""pptr 用户相关 RPC 请求/响应契约（兼容转发层）。

实际定义已迁移至 `bili_common.rpc.pptr_user`（按系统分模块组织），
本文件仅作为兼容入口 re-export，保证存量引用零改动。
"""

from bili_common.rpc.pptr_user import (
    PPTR_USER_RPC_CONTRACT,
    PptrAddDailyLoginExpParams,
    PptrAddDailyLoginExpResult,
    PptrAddExpParams,
    PptrAddExpResult,
    PptrAddUsernameRecordParams,
    PptrAddUsernameRecordResult,
    PptrCreateUserParams,
    PptrCreateUserResult,
    PptrGetUserCardParams,
    PptrGetUserInfoParams,
    PptrGetUserLevelParams,
    PptrGetUserNavParams,
    PptrSetResult,
    PptrSetUserDetailParams,
    PptrSetUserLevelParams,
    PptrSetUserRoleParams,
    PptrUpdateUserInfoParams,
    PptrUpdateUserInfoResult,
    PptrUserCard,
    PptrUserLevelInfo,
    PptrUserProfile,
    PptrUserSearchResult,
    UserSearchParams,
    pptr_routing_key_for,
)

__all__ = [
    "pptr_routing_key_for",
    "PptrGetUserInfoParams",
    "PptrGetUserCardParams",
    "PptrCreateUserParams",
    "PptrUpdateUserInfoParams",
    "PptrUserCard",
    "PptrUserProfile",
    "PptrCreateUserResult",
    "PptrUpdateUserInfoResult",
    "PptrGetUserLevelParams",
    "PptrUserLevelInfo",
    "PptrSetUserLevelParams",
    "PptrSetUserDetailParams",
    "PptrSetUserRoleParams",
    "PptrSetResult",
    "PptrAddExpParams",
    "PptrAddExpResult",
    "PptrAddDailyLoginExpParams",
    "PptrAddDailyLoginExpResult",
    "PptrAddUsernameRecordParams",
    "PptrAddUsernameRecordResult",
    "PptrGetUserNavParams",
    "PPTR_USER_RPC_CONTRACT",
    "UserSearchParams",
    "PptrUserSearchResult",
]
