"""auto detect model changes

Revision ID: 6a04486b2b42
Revises: dd7ff9eafd99
Create Date: 2026-07-02 14:35:20.788982

数据库: 请在运行 alembic 时通过 -x db=xxx 指定，version_table 由 env.py 自动管理。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic import context
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6a04486b2b42'
down_revision: Union[str, Sequence[str], None] = 'dd7ff9eafd99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema (and optionally data)."""
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get("data", None):
        data_upgrades()


def downgrade() -> None:
    """Downgrade schema (and optionally data)."""
    if context.get_x_argument(as_dictionary=True).get("data", None):
        data_downgrades()
    schema_downgrades()


def schema_upgrades() -> None:
    """Schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_lot_extra_info', sa.Column('need_comment', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=False, comment='是否需要评论: 1-是, 0-否'))
    op.add_column('t_lot_extra_info', sa.Column('need_repost', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=False, comment='是否需要转发: 1-是, 0-否'))
    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """Schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_lot_extra_info', 'need_repost')
    op.drop_column('t_lot_extra_info', 'need_comment')
    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""
    pass


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
    pass
