# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bilibili/dagw/component/avatar/v1/plugin.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bilibili.dagw.component.avatar.common import common_pb2 as bilibili_dot_dagw_dot_component_dot_avatar_dot_common_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bilibili/dagw/component/avatar/v1/plugin.proto',
  package='bilibili.dagw.component.avatar.v1.plugin',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n.bilibili/dagw/component/avatar/v1/plugin.proto\x12(bilibili.dagw.component.avatar.v1.plugin\x1a\x32\x62ilibili/dagw/component/avatar/common/common.proto\"\x7f\n\x18\x43ommentDoubleClickConfig\x12J\n\x0binteraction\x18\x01 \x01(\x0b\x32\x35.bilibili.dagw.component.avatar.v1.plugin.Interaction\x12\x17\n\x0f\x61nimation_scale\x18\x02 \x01(\x01\"U\n\nGyroConfig\x12G\n\tgyroscope\x18\x01 \x01(\x0b\x32\x34.bilibili.dagw.component.avatar.v1.plugin.NFTImageV2\"\x94\x01\n\x12GyroscopeContentV2\x12\x10\n\x08\x66ile_url\x18\x01 \x01(\t\x12\r\n\x05scale\x18\x02 \x01(\x02\x12]\n\x14physical_orientation\x18\x03 \x03(\x0b\x32?.bilibili.dagw.component.avatar.v1.plugin.PhysicalOrientationV2\"y\n\x11GyroscopeEntityV2\x12\x14\n\x0c\x64isplay_type\x18\x01 \x01(\t\x12N\n\x08\x63ontents\x18\x02 \x03(\x0b\x32<.bilibili.dagw.component.avatar.v1.plugin.GyroscopeContentV2\"S\n\x0bInteraction\x12\x0e\n\x06nft_id\x18\x01 \x01(\t\x12\x0f\n\x07\x65nabled\x18\x02 \x01(\x08\x12\r\n\x05itype\x18\x03 \x01(\t\x12\x14\n\x0cmetadata_url\x18\x04 \x01(\t\"\"\n\x0fLiveAnimeConfig\x12\x0f\n\x07is_live\x18\x01 \x01(\x08\"\xb6\x01\n\rLiveAnimeItem\x12\x41\n\x05\x63olor\x18\x01 \x01(\x0b\x32\x32.bilibili.dagw.component.avatar.common.ColorConfig\x12\x13\n\x0bstart_ratio\x18\x02 \x01(\x01\x12\x11\n\tend_ratio\x18\x03 \x01(\x01\x12\x14\n\x0cstart_stroke\x18\x04 \x01(\x01\x12\x15\n\rstart_opacity\x18\x05 \x01(\x01\x12\r\n\x05phase\x18\x06 \x01(\x03\"\\\n\nNFTImageV2\x12N\n\tgyroscope\x18\x01 \x03(\x0b\x32;.bilibili.dagw.component.avatar.v1.plugin.GyroscopeEntityV2\"<\n\x1cPhysicalOrientationAnimation\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0e\n\x06\x62\x65zier\x18\x03 \x01(\t\"\x81\x01\n\x15PhysicalOrientationV2\x12\x0c\n\x04type\x18\x01 \x01(\t\x12Z\n\nanimations\x18\x03 \x03(\x0b\x32\x46.bilibili.dagw.component.avatar.v1.plugin.PhysicalOrientationAnimationb\x06proto3'
  ,
  dependencies=[bilibili_dot_dagw_dot_component_dot_avatar_dot_common_dot_common__pb2.DESCRIPTOR,])




_COMMENTDOUBLECLICKCONFIG = _descriptor.Descriptor(
  name='CommentDoubleClickConfig',
  full_name='bilibili.dagw.component.avatar.v1.plugin.CommentDoubleClickConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='interaction', full_name='bilibili.dagw.component.avatar.v1.plugin.CommentDoubleClickConfig.interaction', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='animation_scale', full_name='bilibili.dagw.component.avatar.v1.plugin.CommentDoubleClickConfig.animation_scale', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=271,
)


_GYROCONFIG = _descriptor.Descriptor(
  name='GyroConfig',
  full_name='bilibili.dagw.component.avatar.v1.plugin.GyroConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gyroscope', full_name='bilibili.dagw.component.avatar.v1.plugin.GyroConfig.gyroscope', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=358,
)


_GYROSCOPECONTENTV2 = _descriptor.Descriptor(
  name='GyroscopeContentV2',
  full_name='bilibili.dagw.component.avatar.v1.plugin.GyroscopeContentV2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_url', full_name='bilibili.dagw.component.avatar.v1.plugin.GyroscopeContentV2.file_url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='scale', full_name='bilibili.dagw.component.avatar.v1.plugin.GyroscopeContentV2.scale', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='physical_orientation', full_name='bilibili.dagw.component.avatar.v1.plugin.GyroscopeContentV2.physical_orientation', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=361,
  serialized_end=509,
)


_GYROSCOPEENTITYV2 = _descriptor.Descriptor(
  name='GyroscopeEntityV2',
  full_name='bilibili.dagw.component.avatar.v1.plugin.GyroscopeEntityV2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='display_type', full_name='bilibili.dagw.component.avatar.v1.plugin.GyroscopeEntityV2.display_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contents', full_name='bilibili.dagw.component.avatar.v1.plugin.GyroscopeEntityV2.contents', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=511,
  serialized_end=632,
)


_INTERACTION = _descriptor.Descriptor(
  name='Interaction',
  full_name='bilibili.dagw.component.avatar.v1.plugin.Interaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nft_id', full_name='bilibili.dagw.component.avatar.v1.plugin.Interaction.nft_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enabled', full_name='bilibili.dagw.component.avatar.v1.plugin.Interaction.enabled', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='itype', full_name='bilibili.dagw.component.avatar.v1.plugin.Interaction.itype', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='metadata_url', full_name='bilibili.dagw.component.avatar.v1.plugin.Interaction.metadata_url', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=634,
  serialized_end=717,
)


_LIVEANIMECONFIG = _descriptor.Descriptor(
  name='LiveAnimeConfig',
  full_name='bilibili.dagw.component.avatar.v1.plugin.LiveAnimeConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_live', full_name='bilibili.dagw.component.avatar.v1.plugin.LiveAnimeConfig.is_live', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=719,
  serialized_end=753,
)


_LIVEANIMEITEM = _descriptor.Descriptor(
  name='LiveAnimeItem',
  full_name='bilibili.dagw.component.avatar.v1.plugin.LiveAnimeItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='color', full_name='bilibili.dagw.component.avatar.v1.plugin.LiveAnimeItem.color', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_ratio', full_name='bilibili.dagw.component.avatar.v1.plugin.LiveAnimeItem.start_ratio', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_ratio', full_name='bilibili.dagw.component.avatar.v1.plugin.LiveAnimeItem.end_ratio', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_stroke', full_name='bilibili.dagw.component.avatar.v1.plugin.LiveAnimeItem.start_stroke', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_opacity', full_name='bilibili.dagw.component.avatar.v1.plugin.LiveAnimeItem.start_opacity', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='phase', full_name='bilibili.dagw.component.avatar.v1.plugin.LiveAnimeItem.phase', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=756,
  serialized_end=938,
)


_NFTIMAGEV2 = _descriptor.Descriptor(
  name='NFTImageV2',
  full_name='bilibili.dagw.component.avatar.v1.plugin.NFTImageV2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gyroscope', full_name='bilibili.dagw.component.avatar.v1.plugin.NFTImageV2.gyroscope', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=940,
  serialized_end=1032,
)


_PHYSICALORIENTATIONANIMATION = _descriptor.Descriptor(
  name='PhysicalOrientationAnimation',
  full_name='bilibili.dagw.component.avatar.v1.plugin.PhysicalOrientationAnimation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='bilibili.dagw.component.avatar.v1.plugin.PhysicalOrientationAnimation.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bezier', full_name='bilibili.dagw.component.avatar.v1.plugin.PhysicalOrientationAnimation.bezier', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1034,
  serialized_end=1094,
)


_PHYSICALORIENTATIONV2 = _descriptor.Descriptor(
  name='PhysicalOrientationV2',
  full_name='bilibili.dagw.component.avatar.v1.plugin.PhysicalOrientationV2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='bilibili.dagw.component.avatar.v1.plugin.PhysicalOrientationV2.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='animations', full_name='bilibili.dagw.component.avatar.v1.plugin.PhysicalOrientationV2.animations', index=1,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1097,
  serialized_end=1226,
)

_COMMENTDOUBLECLICKCONFIG.fields_by_name['interaction'].message_type = _INTERACTION
_GYROCONFIG.fields_by_name['gyroscope'].message_type = _NFTIMAGEV2
_GYROSCOPECONTENTV2.fields_by_name['physical_orientation'].message_type = _PHYSICALORIENTATIONV2
_GYROSCOPEENTITYV2.fields_by_name['contents'].message_type = _GYROSCOPECONTENTV2
_LIVEANIMEITEM.fields_by_name['color'].message_type = bilibili_dot_dagw_dot_component_dot_avatar_dot_common_dot_common__pb2._COLORCONFIG
_NFTIMAGEV2.fields_by_name['gyroscope'].message_type = _GYROSCOPEENTITYV2
_PHYSICALORIENTATIONV2.fields_by_name['animations'].message_type = _PHYSICALORIENTATIONANIMATION
DESCRIPTOR.message_types_by_name['CommentDoubleClickConfig'] = _COMMENTDOUBLECLICKCONFIG
DESCRIPTOR.message_types_by_name['GyroConfig'] = _GYROCONFIG
DESCRIPTOR.message_types_by_name['GyroscopeContentV2'] = _GYROSCOPECONTENTV2
DESCRIPTOR.message_types_by_name['GyroscopeEntityV2'] = _GYROSCOPEENTITYV2
DESCRIPTOR.message_types_by_name['Interaction'] = _INTERACTION
DESCRIPTOR.message_types_by_name['LiveAnimeConfig'] = _LIVEANIMECONFIG
DESCRIPTOR.message_types_by_name['LiveAnimeItem'] = _LIVEANIMEITEM
DESCRIPTOR.message_types_by_name['NFTImageV2'] = _NFTIMAGEV2
DESCRIPTOR.message_types_by_name['PhysicalOrientationAnimation'] = _PHYSICALORIENTATIONANIMATION
DESCRIPTOR.message_types_by_name['PhysicalOrientationV2'] = _PHYSICALORIENTATIONV2
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CommentDoubleClickConfig = _reflection.GeneratedProtocolMessageType('CommentDoubleClickConfig', (_message.Message,), {
  'DESCRIPTOR' : _COMMENTDOUBLECLICKCONFIG,
  '__module__' : 'bilibili.dagw.component.avatar.v1.plugin_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.dagw.component.avatar.v1.plugin.CommentDoubleClickConfig)
  })
_sym_db.RegisterMessage(CommentDoubleClickConfig)

GyroConfig = _reflection.GeneratedProtocolMessageType('GyroConfig', (_message.Message,), {
  'DESCRIPTOR' : _GYROCONFIG,
  '__module__' : 'bilibili.dagw.component.avatar.v1.plugin_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.dagw.component.avatar.v1.plugin.GyroConfig)
  })
_sym_db.RegisterMessage(GyroConfig)

GyroscopeContentV2 = _reflection.GeneratedProtocolMessageType('GyroscopeContentV2', (_message.Message,), {
  'DESCRIPTOR' : _GYROSCOPECONTENTV2,
  '__module__' : 'bilibili.dagw.component.avatar.v1.plugin_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.dagw.component.avatar.v1.plugin.GyroscopeContentV2)
  })
_sym_db.RegisterMessage(GyroscopeContentV2)

GyroscopeEntityV2 = _reflection.GeneratedProtocolMessageType('GyroscopeEntityV2', (_message.Message,), {
  'DESCRIPTOR' : _GYROSCOPEENTITYV2,
  '__module__' : 'bilibili.dagw.component.avatar.v1.plugin_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.dagw.component.avatar.v1.plugin.GyroscopeEntityV2)
  })
_sym_db.RegisterMessage(GyroscopeEntityV2)

Interaction = _reflection.GeneratedProtocolMessageType('Interaction', (_message.Message,), {
  'DESCRIPTOR' : _INTERACTION,
  '__module__' : 'bilibili.dagw.component.avatar.v1.plugin_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.dagw.component.avatar.v1.plugin.Interaction)
  })
_sym_db.RegisterMessage(Interaction)

LiveAnimeConfig = _reflection.GeneratedProtocolMessageType('LiveAnimeConfig', (_message.Message,), {
  'DESCRIPTOR' : _LIVEANIMECONFIG,
  '__module__' : 'bilibili.dagw.component.avatar.v1.plugin_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.dagw.component.avatar.v1.plugin.LiveAnimeConfig)
  })
_sym_db.RegisterMessage(LiveAnimeConfig)

LiveAnimeItem = _reflection.GeneratedProtocolMessageType('LiveAnimeItem', (_message.Message,), {
  'DESCRIPTOR' : _LIVEANIMEITEM,
  '__module__' : 'bilibili.dagw.component.avatar.v1.plugin_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.dagw.component.avatar.v1.plugin.LiveAnimeItem)
  })
_sym_db.RegisterMessage(LiveAnimeItem)

NFTImageV2 = _reflection.GeneratedProtocolMessageType('NFTImageV2', (_message.Message,), {
  'DESCRIPTOR' : _NFTIMAGEV2,
  '__module__' : 'bilibili.dagw.component.avatar.v1.plugin_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.dagw.component.avatar.v1.plugin.NFTImageV2)
  })
_sym_db.RegisterMessage(NFTImageV2)

PhysicalOrientationAnimation = _reflection.GeneratedProtocolMessageType('PhysicalOrientationAnimation', (_message.Message,), {
  'DESCRIPTOR' : _PHYSICALORIENTATIONANIMATION,
  '__module__' : 'bilibili.dagw.component.avatar.v1.plugin_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.dagw.component.avatar.v1.plugin.PhysicalOrientationAnimation)
  })
_sym_db.RegisterMessage(PhysicalOrientationAnimation)

PhysicalOrientationV2 = _reflection.GeneratedProtocolMessageType('PhysicalOrientationV2', (_message.Message,), {
  'DESCRIPTOR' : _PHYSICALORIENTATIONV2,
  '__module__' : 'bilibili.dagw.component.avatar.v1.plugin_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.dagw.component.avatar.v1.plugin.PhysicalOrientationV2)
  })
_sym_db.RegisterMessage(PhysicalOrientationV2)


# @@protoc_insertion_point(module_scope)
