# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: bilibili/app/resource/privacy/v1/api.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import bilibili.app.resource.privacy.v1.api_pb2


class PrivacyBase(abc.ABC):

    @abc.abstractmethod
    async def PrivacyConfig(self, stream: 'grpclib.server.Stream[bilibili.app.resource.privacy.v1.api_pb2.NoArgRequest, bilibili.app.resource.privacy.v1.api_pb2.PrivacyConfigReply]') -> None:
        pass

    @abc.abstractmethod
    async def SetPrivacyConfig(self, stream: 'grpclib.server.Stream[bilibili.app.resource.privacy.v1.api_pb2.SetPrivacyConfigRequest, bilibili.app.resource.privacy.v1.api_pb2.NoReply]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/bilibili.app.resource.privacy.v1.Privacy/PrivacyConfig': grpclib.const.Handler(
                self.PrivacyConfig,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.resource.privacy.v1.api_pb2.NoArgRequest,
                bilibili.app.resource.privacy.v1.api_pb2.PrivacyConfigReply,
            ),
            '/bilibili.app.resource.privacy.v1.Privacy/SetPrivacyConfig': grpclib.const.Handler(
                self.SetPrivacyConfig,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.resource.privacy.v1.api_pb2.SetPrivacyConfigRequest,
                bilibili.app.resource.privacy.v1.api_pb2.NoReply,
            ),
        }


class PrivacyStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.PrivacyConfig = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.resource.privacy.v1.Privacy/PrivacyConfig',
            bilibili.app.resource.privacy.v1.api_pb2.NoArgRequest,
            bilibili.app.resource.privacy.v1.api_pb2.PrivacyConfigReply,
        )
        self.SetPrivacyConfig = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.resource.privacy.v1.Privacy/SetPrivacyConfig',
            bilibili.app.resource.privacy.v1.api_pb2.SetPrivacyConfigRequest,
            bilibili.app.resource.privacy.v1.api_pb2.NoReply,
        )
