# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/protobuf/editions/codegen_tests/proto2_packed.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/protobuf/editions/codegen_tests/proto2_packed.proto',
  package='protobuf_editions_test.proto2',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n:google/protobuf/editions/codegen_tests/proto2_packed.proto\x12\x1dprotobuf_editions_test.proto2\"\'\n\x0cProto2Packed\x12\x17\n\x0bint32_field\x18\x01 \x03(\x05\x42\x02\x10\x01'
)




_PROTO2PACKED = _descriptor.Descriptor(
  name='Proto2Packed',
  full_name='protobuf_editions_test.proto2.Proto2Packed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='int32_field', full_name='protobuf_editions_test.proto2.Proto2Packed.int32_field', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=132,
)

DESCRIPTOR.message_types_by_name['Proto2Packed'] = _PROTO2PACKED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Proto2Packed = _reflection.GeneratedProtocolMessageType('Proto2Packed', (_message.Message,), {
  'DESCRIPTOR' : _PROTO2PACKED,
  '__module__' : 'google.protobuf.editions.codegen_tests.proto2_packed_pb2'
  # @@protoc_insertion_point(class_scope:protobuf_editions_test.proto2.Proto2Packed)
  })
_sym_db.RegisterMessage(Proto2Packed)


_PROTO2PACKED.fields_by_name['int32_field']._options = None
# @@protoc_insertion_point(module_scope)
