# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: google/protobuf/editions/codegen_tests/proto2_unpacked.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'google/protobuf/editions/codegen_tests/proto2_unpacked.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<google/protobuf/editions/codegen_tests/proto2_unpacked.proto\x12\x1dprotobuf_editions_test.proto2\"\xb3\x01\n\x0eProto2Unpacked\x12\x13\n\x0bint32_field\x18\x01 \x03(\x05\x12\x14\n\x0cstring_field\x18\x02 \x03(\t\x12S\n\x11sub_message_field\x18\x03 \x03(\x0b\x32\x38.protobuf_editions_test.proto2.Proto2Unpacked.SubMessage\x1a!\n\nSubMessage\x12\x13\n\x0bint32_field\x18\x01 \x01(\x05')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.protobuf.editions.codegen_tests.proto2_unpacked_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROTO2UNPACKED']._serialized_start=96
  _globals['_PROTO2UNPACKED']._serialized_end=275
  _globals['_PROTO2UNPACKED_SUBMESSAGE']._serialized_start=242
  _globals['_PROTO2UNPACKED_SUBMESSAGE']._serialized_end=275
# @@protoc_insertion_point(module_scope)
