# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/protobuf/editions/codegen_tests/proto2_proto3_enum.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf.editions.codegen_tests import proto3_enum_pb2 as google_dot_protobuf_dot_editions_dot_codegen__tests_dot_proto3__enum__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/protobuf/editions/codegen_tests/proto2_proto3_enum.proto',
  package='protobuf_editions_test.proto2',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n?google/protobuf/editions/codegen_tests/proto2_proto3_enum.proto\x12\x1dprotobuf_editions_test.proto2\x1a\x38google/protobuf/editions/codegen_tests/proto3_enum.proto\"\xa6\x01\n\x19Proto2ImportedEnumMessage\x12=\n\nenum_field\x18\x01 \x01(\x0e\x32).protobuf_editions_test.proto3.Proto3Enum\x12J\n\x12\x65num_field_default\x18\x02 \x01(\x0e\x32).protobuf_editions_test.proto3.Proto3Enum:\x03\x42\x41Z'
  ,
  dependencies=[google_dot_protobuf_dot_editions_dot_codegen__tests_dot_proto3__enum__pb2.DESCRIPTOR,])




_PROTO2IMPORTEDENUMMESSAGE = _descriptor.Descriptor(
  name='Proto2ImportedEnumMessage',
  full_name='protobuf_editions_test.proto2.Proto2ImportedEnumMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='enum_field', full_name='protobuf_editions_test.proto2.Proto2ImportedEnumMessage.enum_field', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enum_field_default', full_name='protobuf_editions_test.proto2.Proto2ImportedEnumMessage.enum_field_default', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=323,
)

_PROTO2IMPORTEDENUMMESSAGE.fields_by_name['enum_field'].enum_type = google_dot_protobuf_dot_editions_dot_codegen__tests_dot_proto3__enum__pb2._PROTO3ENUM
_PROTO2IMPORTEDENUMMESSAGE.fields_by_name['enum_field_default'].enum_type = google_dot_protobuf_dot_editions_dot_codegen__tests_dot_proto3__enum__pb2._PROTO3ENUM
DESCRIPTOR.message_types_by_name['Proto2ImportedEnumMessage'] = _PROTO2IMPORTEDENUMMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Proto2ImportedEnumMessage = _reflection.GeneratedProtocolMessageType('Proto2ImportedEnumMessage', (_message.Message,), {
  'DESCRIPTOR' : _PROTO2IMPORTEDENUMMESSAGE,
  '__module__' : 'google.protobuf.editions.codegen_tests.proto2_proto3_enum_pb2'
  # @@protoc_insertion_point(class_scope:protobuf_editions_test.proto2.Proto2ImportedEnumMessage)
  })
_sym_db.RegisterMessage(Proto2ImportedEnumMessage)


# @@protoc_insertion_point(module_scope)
