# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: bilibili/app/dynamic/v2/dynamic.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import google.protobuf.any_pb2
import bilibili.app.archive.middleware.v1.preload_pb2
import bilibili.dagw.component.avatar.v1.avatar_pb2
import bilibili.app.dynamic.v2.dynamic_pb2


class DynamicBase(abc.ABC):

    @abc.abstractmethod
    async def AlumniDynamics(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.AlumniDynamicsReq, bilibili.app.dynamic.v2.dynamic_pb2.AlumniDynamicsReply]') -> None:
        pass

    @abc.abstractmethod
    async def CampusBillBoard(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.CampusBillBoardReq, bilibili.app.dynamic.v2.dynamic_pb2.CampusBillBoardReply]') -> None:
        pass

    @abc.abstractmethod
    async def CampusEntryTab(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.CampusEntryTabReq, bilibili.app.dynamic.v2.dynamic_pb2.CampusEntryTabResp]') -> None:
        pass

    @abc.abstractmethod
    async def CampusFeedback(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.CampusFeedbackReq, bilibili.app.dynamic.v2.dynamic_pb2.CampusFeedbackReply]') -> None:
        pass

    @abc.abstractmethod
    async def CampusHomePages(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.CampusHomePagesReq, bilibili.app.dynamic.v2.dynamic_pb2.CampusHomePagesReply]') -> None:
        pass

    @abc.abstractmethod
    async def CampusMateLikeList(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.CampusMateLikeListReq, bilibili.app.dynamic.v2.dynamic_pb2.CampusMateLikeListReply]') -> None:
        pass

    @abc.abstractmethod
    async def CampusMngDetail(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.CampusMngDetailReq, bilibili.app.dynamic.v2.dynamic_pb2.CampusMngDetailReply]') -> None:
        pass

    @abc.abstractmethod
    async def CampusMngQuizOperate(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.CampusMngQuizOperateReq, bilibili.app.dynamic.v2.dynamic_pb2.CampusMngQuizOperateReply]') -> None:
        pass

    @abc.abstractmethod
    async def CampusMngSubmit(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.CampusMngSubmitReq, bilibili.app.dynamic.v2.dynamic_pb2.CampusMngSubmitReply]') -> None:
        pass

    @abc.abstractmethod
    async def CampusRcmd(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.CampusRcmdReq, bilibili.app.dynamic.v2.dynamic_pb2.CampusRcmdReply]') -> None:
        pass

    @abc.abstractmethod
    async def CampusRcmdFeed(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.CampusRcmdFeedReq, bilibili.app.dynamic.v2.dynamic_pb2.CampusRcmdFeedReply]') -> None:
        pass

    @abc.abstractmethod
    async def CampusRecommend(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.CampusRecommendReq, bilibili.app.dynamic.v2.dynamic_pb2.CampusRecommendReply]') -> None:
        pass

    @abc.abstractmethod
    async def CampusRedDot(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.CampusRedDotReq, bilibili.app.dynamic.v2.dynamic_pb2.CampusRedDotReply]') -> None:
        pass

    @abc.abstractmethod
    async def CampusSquare(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.CampusSquareReq, bilibili.app.dynamic.v2.dynamic_pb2.CampusSquareReply]') -> None:
        pass

    @abc.abstractmethod
    async def CampusTopicRcmdFeed(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.CampusTopicRcmdFeedReq, bilibili.app.dynamic.v2.dynamic_pb2.CampusTopicRcmdFeedReply]') -> None:
        pass

    @abc.abstractmethod
    async def DynAdditionCommonFollow(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.DynAdditionCommonFollowReq, bilibili.app.dynamic.v2.dynamic_pb2.DynAdditionCommonFollowReply]') -> None:
        pass

    @abc.abstractmethod
    async def DynAll(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.DynAllReq, bilibili.app.dynamic.v2.dynamic_pb2.DynAllReply]') -> None:
        pass

    @abc.abstractmethod
    async def DynAllPersonal(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.DynAllPersonalReq, bilibili.app.dynamic.v2.dynamic_pb2.DynAllPersonalReply]') -> None:
        pass

    @abc.abstractmethod
    async def DynAllUpdOffset(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.DynAllUpdOffsetReq, bilibili.app.dynamic.v2.dynamic_pb2.NoReply]') -> None:
        pass

    @abc.abstractmethod
    async def DynDetail(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.DynDetailReq, bilibili.app.dynamic.v2.dynamic_pb2.DynDetailReply]') -> None:
        pass

    @abc.abstractmethod
    async def DynDetails(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.DynDetailsReq, bilibili.app.dynamic.v2.dynamic_pb2.DynDetailsReply]') -> None:
        pass

    @abc.abstractmethod
    async def DynFakeCard(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.DynFakeCardReq, bilibili.app.dynamic.v2.dynamic_pb2.DynFakeCardReply]') -> None:
        pass

    @abc.abstractmethod
    async def DynFriend(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.DynFriendReq, bilibili.app.dynamic.v2.dynamic_pb2.DynFriendReply]') -> None:
        pass

    @abc.abstractmethod
    async def DynLight(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.DynLightReq, bilibili.app.dynamic.v2.dynamic_pb2.DynLightReply]') -> None:
        pass

    @abc.abstractmethod
    async def DynMixUpListViewMore(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.DynMixUpListViewMoreReq, bilibili.app.dynamic.v2.dynamic_pb2.DynMixUpListViewMoreReply]') -> None:
        pass

    @abc.abstractmethod
    async def DynRcmdUpExchange(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.DynRcmdUpExchangeReq, bilibili.app.dynamic.v2.dynamic_pb2.DynRcmdUpExchangeReply]') -> None:
        pass

    @abc.abstractmethod
    async def DynSearch(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.DynSearchReq, bilibili.app.dynamic.v2.dynamic_pb2.DynSearchReply]') -> None:
        pass

    @abc.abstractmethod
    async def DynServerDetails(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.DynServerDetailsReq, bilibili.app.dynamic.v2.dynamic_pb2.DynServerDetailsReply]') -> None:
        pass

    @abc.abstractmethod
    async def DynSpace(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.DynSpaceReq, bilibili.app.dynamic.v2.dynamic_pb2.DynSpaceRsp]') -> None:
        pass

    @abc.abstractmethod
    async def DynSpaceSearchDetails(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.DynSpaceSearchDetailsReq, bilibili.app.dynamic.v2.dynamic_pb2.DynSpaceSearchDetailsReply]') -> None:
        pass

    @abc.abstractmethod
    async def DynTab(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.DynTabReq, bilibili.app.dynamic.v2.dynamic_pb2.DynTabReply]') -> None:
        pass

    @abc.abstractmethod
    async def DynThumb(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.DynThumbReq, bilibili.app.dynamic.v2.dynamic_pb2.NoReply]') -> None:
        pass

    @abc.abstractmethod
    async def DynUnLoginRcmd(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.DynRcmdReq, bilibili.app.dynamic.v2.dynamic_pb2.DynRcmdReply]') -> None:
        pass

    @abc.abstractmethod
    async def DynVideo(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.DynVideoReq, bilibili.app.dynamic.v2.dynamic_pb2.DynVideoReply]') -> None:
        pass

    @abc.abstractmethod
    async def DynVideoPersonal(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.DynVideoPersonalReq, bilibili.app.dynamic.v2.dynamic_pb2.DynVideoPersonalReply]') -> None:
        pass

    @abc.abstractmethod
    async def DynVideoUpdOffset(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.DynVideoUpdOffsetReq, bilibili.app.dynamic.v2.dynamic_pb2.NoReply]') -> None:
        pass

    @abc.abstractmethod
    async def DynVote(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.DynVoteReq, bilibili.app.dynamic.v2.dynamic_pb2.DynVoteReply]') -> None:
        pass

    @abc.abstractmethod
    async def FeedFilter(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.FeedFilterReq, bilibili.app.dynamic.v2.dynamic_pb2.FeedFilterReply]') -> None:
        pass

    @abc.abstractmethod
    async def FetchTabSetting(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.NoReq, bilibili.app.dynamic.v2.dynamic_pb2.FetchTabSettingReply]') -> None:
        pass

    @abc.abstractmethod
    async def HomeSubscribe(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.HomeSubscribeReq, bilibili.app.dynamic.v2.dynamic_pb2.HomeSubscribeReply]') -> None:
        pass

    @abc.abstractmethod
    async def LbsPoi(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.LbsPoiReq, bilibili.app.dynamic.v2.dynamic_pb2.LbsPoiReply]') -> None:
        pass

    @abc.abstractmethod
    async def LegacyTopicFeed(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.LegacyTopicFeedReq, bilibili.app.dynamic.v2.dynamic_pb2.LegacyTopicFeedReply]') -> None:
        pass

    @abc.abstractmethod
    async def LikeList(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.LikeListReq, bilibili.app.dynamic.v2.dynamic_pb2.LikeListReply]') -> None:
        pass

    @abc.abstractmethod
    async def OfficialAccounts(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.OfficialAccountsReq, bilibili.app.dynamic.v2.dynamic_pb2.OfficialAccountsReply]') -> None:
        pass

    @abc.abstractmethod
    async def OfficialDynamics(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.OfficialDynamicsReq, bilibili.app.dynamic.v2.dynamic_pb2.OfficialDynamicsReply]') -> None:
        pass

    @abc.abstractmethod
    async def ReactionList(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.ReactionListReq, bilibili.app.dynamic.v2.dynamic_pb2.ReactionListReply]') -> None:
        pass

    @abc.abstractmethod
    async def RepostList(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.RepostListReq, bilibili.app.dynamic.v2.dynamic_pb2.RepostListRsp]') -> None:
        pass

    @abc.abstractmethod
    async def SchoolRecommend(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.SchoolRecommendReq, bilibili.app.dynamic.v2.dynamic_pb2.SchoolRecommendReply]') -> None:
        pass

    @abc.abstractmethod
    async def SchoolSearch(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.SchoolSearchReq, bilibili.app.dynamic.v2.dynamic_pb2.SchoolSearchReply]') -> None:
        pass

    @abc.abstractmethod
    async def SetDecision(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.SetDecisionReq, bilibili.app.dynamic.v2.dynamic_pb2.NoReply]') -> None:
        pass

    @abc.abstractmethod
    async def SetRecentCampus(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.SetRecentCampusReq, bilibili.app.dynamic.v2.dynamic_pb2.NoReply]') -> None:
        pass

    @abc.abstractmethod
    async def SubscribeCampus(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.SubscribeCampusReq, bilibili.app.dynamic.v2.dynamic_pb2.NoReply]') -> None:
        pass

    @abc.abstractmethod
    async def TopicList(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.TopicListReq, bilibili.app.dynamic.v2.dynamic_pb2.TopicListReply]') -> None:
        pass

    @abc.abstractmethod
    async def TopicSquare(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.TopicSquareReq, bilibili.app.dynamic.v2.dynamic_pb2.TopicSquareReply]') -> None:
        pass

    @abc.abstractmethod
    async def UnfollowMatch(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.UnfollowMatchReq, bilibili.app.dynamic.v2.dynamic_pb2.NoReply]') -> None:
        pass

    @abc.abstractmethod
    async def UpdateTabSetting(self, stream: 'grpclib.server.Stream[bilibili.app.dynamic.v2.dynamic_pb2.UpdateTabSettingReq, bilibili.app.dynamic.v2.dynamic_pb2.NoReply]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/bilibili.app.dynamic.v2.Dynamic/AlumniDynamics': grpclib.const.Handler(
                self.AlumniDynamics,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.AlumniDynamicsReq,
                bilibili.app.dynamic.v2.dynamic_pb2.AlumniDynamicsReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/CampusBillBoard': grpclib.const.Handler(
                self.CampusBillBoard,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.CampusBillBoardReq,
                bilibili.app.dynamic.v2.dynamic_pb2.CampusBillBoardReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/CampusEntryTab': grpclib.const.Handler(
                self.CampusEntryTab,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.CampusEntryTabReq,
                bilibili.app.dynamic.v2.dynamic_pb2.CampusEntryTabResp,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/CampusFeedback': grpclib.const.Handler(
                self.CampusFeedback,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.CampusFeedbackReq,
                bilibili.app.dynamic.v2.dynamic_pb2.CampusFeedbackReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/CampusHomePages': grpclib.const.Handler(
                self.CampusHomePages,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.CampusHomePagesReq,
                bilibili.app.dynamic.v2.dynamic_pb2.CampusHomePagesReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/CampusMateLikeList': grpclib.const.Handler(
                self.CampusMateLikeList,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.CampusMateLikeListReq,
                bilibili.app.dynamic.v2.dynamic_pb2.CampusMateLikeListReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/CampusMngDetail': grpclib.const.Handler(
                self.CampusMngDetail,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.CampusMngDetailReq,
                bilibili.app.dynamic.v2.dynamic_pb2.CampusMngDetailReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/CampusMngQuizOperate': grpclib.const.Handler(
                self.CampusMngQuizOperate,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.CampusMngQuizOperateReq,
                bilibili.app.dynamic.v2.dynamic_pb2.CampusMngQuizOperateReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/CampusMngSubmit': grpclib.const.Handler(
                self.CampusMngSubmit,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.CampusMngSubmitReq,
                bilibili.app.dynamic.v2.dynamic_pb2.CampusMngSubmitReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/CampusRcmd': grpclib.const.Handler(
                self.CampusRcmd,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.CampusRcmdReq,
                bilibili.app.dynamic.v2.dynamic_pb2.CampusRcmdReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/CampusRcmdFeed': grpclib.const.Handler(
                self.CampusRcmdFeed,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.CampusRcmdFeedReq,
                bilibili.app.dynamic.v2.dynamic_pb2.CampusRcmdFeedReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/CampusRecommend': grpclib.const.Handler(
                self.CampusRecommend,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.CampusRecommendReq,
                bilibili.app.dynamic.v2.dynamic_pb2.CampusRecommendReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/CampusRedDot': grpclib.const.Handler(
                self.CampusRedDot,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.CampusRedDotReq,
                bilibili.app.dynamic.v2.dynamic_pb2.CampusRedDotReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/CampusSquare': grpclib.const.Handler(
                self.CampusSquare,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.CampusSquareReq,
                bilibili.app.dynamic.v2.dynamic_pb2.CampusSquareReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/CampusTopicRcmdFeed': grpclib.const.Handler(
                self.CampusTopicRcmdFeed,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.CampusTopicRcmdFeedReq,
                bilibili.app.dynamic.v2.dynamic_pb2.CampusTopicRcmdFeedReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/DynAdditionCommonFollow': grpclib.const.Handler(
                self.DynAdditionCommonFollow,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.DynAdditionCommonFollowReq,
                bilibili.app.dynamic.v2.dynamic_pb2.DynAdditionCommonFollowReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/DynAll': grpclib.const.Handler(
                self.DynAll,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.DynAllReq,
                bilibili.app.dynamic.v2.dynamic_pb2.DynAllReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/DynAllPersonal': grpclib.const.Handler(
                self.DynAllPersonal,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.DynAllPersonalReq,
                bilibili.app.dynamic.v2.dynamic_pb2.DynAllPersonalReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/DynAllUpdOffset': grpclib.const.Handler(
                self.DynAllUpdOffset,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.DynAllUpdOffsetReq,
                bilibili.app.dynamic.v2.dynamic_pb2.NoReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/DynDetail': grpclib.const.Handler(
                self.DynDetail,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.DynDetailReq,
                bilibili.app.dynamic.v2.dynamic_pb2.DynDetailReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/DynDetails': grpclib.const.Handler(
                self.DynDetails,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.DynDetailsReq,
                bilibili.app.dynamic.v2.dynamic_pb2.DynDetailsReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/DynFakeCard': grpclib.const.Handler(
                self.DynFakeCard,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.DynFakeCardReq,
                bilibili.app.dynamic.v2.dynamic_pb2.DynFakeCardReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/DynFriend': grpclib.const.Handler(
                self.DynFriend,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.DynFriendReq,
                bilibili.app.dynamic.v2.dynamic_pb2.DynFriendReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/DynLight': grpclib.const.Handler(
                self.DynLight,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.DynLightReq,
                bilibili.app.dynamic.v2.dynamic_pb2.DynLightReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/DynMixUpListViewMore': grpclib.const.Handler(
                self.DynMixUpListViewMore,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.DynMixUpListViewMoreReq,
                bilibili.app.dynamic.v2.dynamic_pb2.DynMixUpListViewMoreReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/DynRcmdUpExchange': grpclib.const.Handler(
                self.DynRcmdUpExchange,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.DynRcmdUpExchangeReq,
                bilibili.app.dynamic.v2.dynamic_pb2.DynRcmdUpExchangeReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/DynSearch': grpclib.const.Handler(
                self.DynSearch,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.DynSearchReq,
                bilibili.app.dynamic.v2.dynamic_pb2.DynSearchReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/DynServerDetails': grpclib.const.Handler(
                self.DynServerDetails,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.DynServerDetailsReq,
                bilibili.app.dynamic.v2.dynamic_pb2.DynServerDetailsReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/DynSpace': grpclib.const.Handler(
                self.DynSpace,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.DynSpaceReq,
                bilibili.app.dynamic.v2.dynamic_pb2.DynSpaceRsp,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/DynSpaceSearchDetails': grpclib.const.Handler(
                self.DynSpaceSearchDetails,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.DynSpaceSearchDetailsReq,
                bilibili.app.dynamic.v2.dynamic_pb2.DynSpaceSearchDetailsReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/DynTab': grpclib.const.Handler(
                self.DynTab,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.DynTabReq,
                bilibili.app.dynamic.v2.dynamic_pb2.DynTabReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/DynThumb': grpclib.const.Handler(
                self.DynThumb,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.DynThumbReq,
                bilibili.app.dynamic.v2.dynamic_pb2.NoReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/DynUnLoginRcmd': grpclib.const.Handler(
                self.DynUnLoginRcmd,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.DynRcmdReq,
                bilibili.app.dynamic.v2.dynamic_pb2.DynRcmdReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/DynVideo': grpclib.const.Handler(
                self.DynVideo,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.DynVideoReq,
                bilibili.app.dynamic.v2.dynamic_pb2.DynVideoReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/DynVideoPersonal': grpclib.const.Handler(
                self.DynVideoPersonal,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.DynVideoPersonalReq,
                bilibili.app.dynamic.v2.dynamic_pb2.DynVideoPersonalReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/DynVideoUpdOffset': grpclib.const.Handler(
                self.DynVideoUpdOffset,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.DynVideoUpdOffsetReq,
                bilibili.app.dynamic.v2.dynamic_pb2.NoReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/DynVote': grpclib.const.Handler(
                self.DynVote,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.DynVoteReq,
                bilibili.app.dynamic.v2.dynamic_pb2.DynVoteReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/FeedFilter': grpclib.const.Handler(
                self.FeedFilter,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.FeedFilterReq,
                bilibili.app.dynamic.v2.dynamic_pb2.FeedFilterReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/FetchTabSetting': grpclib.const.Handler(
                self.FetchTabSetting,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.NoReq,
                bilibili.app.dynamic.v2.dynamic_pb2.FetchTabSettingReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/HomeSubscribe': grpclib.const.Handler(
                self.HomeSubscribe,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.HomeSubscribeReq,
                bilibili.app.dynamic.v2.dynamic_pb2.HomeSubscribeReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/LbsPoi': grpclib.const.Handler(
                self.LbsPoi,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.LbsPoiReq,
                bilibili.app.dynamic.v2.dynamic_pb2.LbsPoiReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/LegacyTopicFeed': grpclib.const.Handler(
                self.LegacyTopicFeed,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.LegacyTopicFeedReq,
                bilibili.app.dynamic.v2.dynamic_pb2.LegacyTopicFeedReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/LikeList': grpclib.const.Handler(
                self.LikeList,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.LikeListReq,
                bilibili.app.dynamic.v2.dynamic_pb2.LikeListReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/OfficialAccounts': grpclib.const.Handler(
                self.OfficialAccounts,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.OfficialAccountsReq,
                bilibili.app.dynamic.v2.dynamic_pb2.OfficialAccountsReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/OfficialDynamics': grpclib.const.Handler(
                self.OfficialDynamics,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.OfficialDynamicsReq,
                bilibili.app.dynamic.v2.dynamic_pb2.OfficialDynamicsReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/ReactionList': grpclib.const.Handler(
                self.ReactionList,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.ReactionListReq,
                bilibili.app.dynamic.v2.dynamic_pb2.ReactionListReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/RepostList': grpclib.const.Handler(
                self.RepostList,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.RepostListReq,
                bilibili.app.dynamic.v2.dynamic_pb2.RepostListRsp,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/SchoolRecommend': grpclib.const.Handler(
                self.SchoolRecommend,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.SchoolRecommendReq,
                bilibili.app.dynamic.v2.dynamic_pb2.SchoolRecommendReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/SchoolSearch': grpclib.const.Handler(
                self.SchoolSearch,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.SchoolSearchReq,
                bilibili.app.dynamic.v2.dynamic_pb2.SchoolSearchReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/SetDecision': grpclib.const.Handler(
                self.SetDecision,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.SetDecisionReq,
                bilibili.app.dynamic.v2.dynamic_pb2.NoReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/SetRecentCampus': grpclib.const.Handler(
                self.SetRecentCampus,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.SetRecentCampusReq,
                bilibili.app.dynamic.v2.dynamic_pb2.NoReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/SubscribeCampus': grpclib.const.Handler(
                self.SubscribeCampus,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.SubscribeCampusReq,
                bilibili.app.dynamic.v2.dynamic_pb2.NoReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/TopicList': grpclib.const.Handler(
                self.TopicList,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.TopicListReq,
                bilibili.app.dynamic.v2.dynamic_pb2.TopicListReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/TopicSquare': grpclib.const.Handler(
                self.TopicSquare,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.TopicSquareReq,
                bilibili.app.dynamic.v2.dynamic_pb2.TopicSquareReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/UnfollowMatch': grpclib.const.Handler(
                self.UnfollowMatch,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.UnfollowMatchReq,
                bilibili.app.dynamic.v2.dynamic_pb2.NoReply,
            ),
            '/bilibili.app.dynamic.v2.Dynamic/UpdateTabSetting': grpclib.const.Handler(
                self.UpdateTabSetting,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.dynamic.v2.dynamic_pb2.UpdateTabSettingReq,
                bilibili.app.dynamic.v2.dynamic_pb2.NoReply,
            ),
        }


class DynamicStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.AlumniDynamics = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/AlumniDynamics',
            bilibili.app.dynamic.v2.dynamic_pb2.AlumniDynamicsReq,
            bilibili.app.dynamic.v2.dynamic_pb2.AlumniDynamicsReply,
        )
        self.CampusBillBoard = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/CampusBillBoard',
            bilibili.app.dynamic.v2.dynamic_pb2.CampusBillBoardReq,
            bilibili.app.dynamic.v2.dynamic_pb2.CampusBillBoardReply,
        )
        self.CampusEntryTab = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/CampusEntryTab',
            bilibili.app.dynamic.v2.dynamic_pb2.CampusEntryTabReq,
            bilibili.app.dynamic.v2.dynamic_pb2.CampusEntryTabResp,
        )
        self.CampusFeedback = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/CampusFeedback',
            bilibili.app.dynamic.v2.dynamic_pb2.CampusFeedbackReq,
            bilibili.app.dynamic.v2.dynamic_pb2.CampusFeedbackReply,
        )
        self.CampusHomePages = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/CampusHomePages',
            bilibili.app.dynamic.v2.dynamic_pb2.CampusHomePagesReq,
            bilibili.app.dynamic.v2.dynamic_pb2.CampusHomePagesReply,
        )
        self.CampusMateLikeList = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/CampusMateLikeList',
            bilibili.app.dynamic.v2.dynamic_pb2.CampusMateLikeListReq,
            bilibili.app.dynamic.v2.dynamic_pb2.CampusMateLikeListReply,
        )
        self.CampusMngDetail = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/CampusMngDetail',
            bilibili.app.dynamic.v2.dynamic_pb2.CampusMngDetailReq,
            bilibili.app.dynamic.v2.dynamic_pb2.CampusMngDetailReply,
        )
        self.CampusMngQuizOperate = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/CampusMngQuizOperate',
            bilibili.app.dynamic.v2.dynamic_pb2.CampusMngQuizOperateReq,
            bilibili.app.dynamic.v2.dynamic_pb2.CampusMngQuizOperateReply,
        )
        self.CampusMngSubmit = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/CampusMngSubmit',
            bilibili.app.dynamic.v2.dynamic_pb2.CampusMngSubmitReq,
            bilibili.app.dynamic.v2.dynamic_pb2.CampusMngSubmitReply,
        )
        self.CampusRcmd = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/CampusRcmd',
            bilibili.app.dynamic.v2.dynamic_pb2.CampusRcmdReq,
            bilibili.app.dynamic.v2.dynamic_pb2.CampusRcmdReply,
        )
        self.CampusRcmdFeed = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/CampusRcmdFeed',
            bilibili.app.dynamic.v2.dynamic_pb2.CampusRcmdFeedReq,
            bilibili.app.dynamic.v2.dynamic_pb2.CampusRcmdFeedReply,
        )
        self.CampusRecommend = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/CampusRecommend',
            bilibili.app.dynamic.v2.dynamic_pb2.CampusRecommendReq,
            bilibili.app.dynamic.v2.dynamic_pb2.CampusRecommendReply,
        )
        self.CampusRedDot = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/CampusRedDot',
            bilibili.app.dynamic.v2.dynamic_pb2.CampusRedDotReq,
            bilibili.app.dynamic.v2.dynamic_pb2.CampusRedDotReply,
        )
        self.CampusSquare = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/CampusSquare',
            bilibili.app.dynamic.v2.dynamic_pb2.CampusSquareReq,
            bilibili.app.dynamic.v2.dynamic_pb2.CampusSquareReply,
        )
        self.CampusTopicRcmdFeed = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/CampusTopicRcmdFeed',
            bilibili.app.dynamic.v2.dynamic_pb2.CampusTopicRcmdFeedReq,
            bilibili.app.dynamic.v2.dynamic_pb2.CampusTopicRcmdFeedReply,
        )
        self.DynAdditionCommonFollow = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/DynAdditionCommonFollow',
            bilibili.app.dynamic.v2.dynamic_pb2.DynAdditionCommonFollowReq,
            bilibili.app.dynamic.v2.dynamic_pb2.DynAdditionCommonFollowReply,
        )
        self.DynAll = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/DynAll',
            bilibili.app.dynamic.v2.dynamic_pb2.DynAllReq,
            bilibili.app.dynamic.v2.dynamic_pb2.DynAllReply,
        )
        self.DynAllPersonal = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/DynAllPersonal',
            bilibili.app.dynamic.v2.dynamic_pb2.DynAllPersonalReq,
            bilibili.app.dynamic.v2.dynamic_pb2.DynAllPersonalReply,
        )
        self.DynAllUpdOffset = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/DynAllUpdOffset',
            bilibili.app.dynamic.v2.dynamic_pb2.DynAllUpdOffsetReq,
            bilibili.app.dynamic.v2.dynamic_pb2.NoReply,
        )
        self.DynDetail = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/DynDetail',
            bilibili.app.dynamic.v2.dynamic_pb2.DynDetailReq,
            bilibili.app.dynamic.v2.dynamic_pb2.DynDetailReply,
        )
        self.DynDetails = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/DynDetails',
            bilibili.app.dynamic.v2.dynamic_pb2.DynDetailsReq,
            bilibili.app.dynamic.v2.dynamic_pb2.DynDetailsReply,
        )
        self.DynFakeCard = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/DynFakeCard',
            bilibili.app.dynamic.v2.dynamic_pb2.DynFakeCardReq,
            bilibili.app.dynamic.v2.dynamic_pb2.DynFakeCardReply,
        )
        self.DynFriend = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/DynFriend',
            bilibili.app.dynamic.v2.dynamic_pb2.DynFriendReq,
            bilibili.app.dynamic.v2.dynamic_pb2.DynFriendReply,
        )
        self.DynLight = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/DynLight',
            bilibili.app.dynamic.v2.dynamic_pb2.DynLightReq,
            bilibili.app.dynamic.v2.dynamic_pb2.DynLightReply,
        )
        self.DynMixUpListViewMore = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/DynMixUpListViewMore',
            bilibili.app.dynamic.v2.dynamic_pb2.DynMixUpListViewMoreReq,
            bilibili.app.dynamic.v2.dynamic_pb2.DynMixUpListViewMoreReply,
        )
        self.DynRcmdUpExchange = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/DynRcmdUpExchange',
            bilibili.app.dynamic.v2.dynamic_pb2.DynRcmdUpExchangeReq,
            bilibili.app.dynamic.v2.dynamic_pb2.DynRcmdUpExchangeReply,
        )
        self.DynSearch = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/DynSearch',
            bilibili.app.dynamic.v2.dynamic_pb2.DynSearchReq,
            bilibili.app.dynamic.v2.dynamic_pb2.DynSearchReply,
        )
        self.DynServerDetails = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/DynServerDetails',
            bilibili.app.dynamic.v2.dynamic_pb2.DynServerDetailsReq,
            bilibili.app.dynamic.v2.dynamic_pb2.DynServerDetailsReply,
        )
        self.DynSpace = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/DynSpace',
            bilibili.app.dynamic.v2.dynamic_pb2.DynSpaceReq,
            bilibili.app.dynamic.v2.dynamic_pb2.DynSpaceRsp,
        )
        self.DynSpaceSearchDetails = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/DynSpaceSearchDetails',
            bilibili.app.dynamic.v2.dynamic_pb2.DynSpaceSearchDetailsReq,
            bilibili.app.dynamic.v2.dynamic_pb2.DynSpaceSearchDetailsReply,
        )
        self.DynTab = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/DynTab',
            bilibili.app.dynamic.v2.dynamic_pb2.DynTabReq,
            bilibili.app.dynamic.v2.dynamic_pb2.DynTabReply,
        )
        self.DynThumb = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/DynThumb',
            bilibili.app.dynamic.v2.dynamic_pb2.DynThumbReq,
            bilibili.app.dynamic.v2.dynamic_pb2.NoReply,
        )
        self.DynUnLoginRcmd = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/DynUnLoginRcmd',
            bilibili.app.dynamic.v2.dynamic_pb2.DynRcmdReq,
            bilibili.app.dynamic.v2.dynamic_pb2.DynRcmdReply,
        )
        self.DynVideo = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/DynVideo',
            bilibili.app.dynamic.v2.dynamic_pb2.DynVideoReq,
            bilibili.app.dynamic.v2.dynamic_pb2.DynVideoReply,
        )
        self.DynVideoPersonal = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/DynVideoPersonal',
            bilibili.app.dynamic.v2.dynamic_pb2.DynVideoPersonalReq,
            bilibili.app.dynamic.v2.dynamic_pb2.DynVideoPersonalReply,
        )
        self.DynVideoUpdOffset = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/DynVideoUpdOffset',
            bilibili.app.dynamic.v2.dynamic_pb2.DynVideoUpdOffsetReq,
            bilibili.app.dynamic.v2.dynamic_pb2.NoReply,
        )
        self.DynVote = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/DynVote',
            bilibili.app.dynamic.v2.dynamic_pb2.DynVoteReq,
            bilibili.app.dynamic.v2.dynamic_pb2.DynVoteReply,
        )
        self.FeedFilter = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/FeedFilter',
            bilibili.app.dynamic.v2.dynamic_pb2.FeedFilterReq,
            bilibili.app.dynamic.v2.dynamic_pb2.FeedFilterReply,
        )
        self.FetchTabSetting = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/FetchTabSetting',
            bilibili.app.dynamic.v2.dynamic_pb2.NoReq,
            bilibili.app.dynamic.v2.dynamic_pb2.FetchTabSettingReply,
        )
        self.HomeSubscribe = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/HomeSubscribe',
            bilibili.app.dynamic.v2.dynamic_pb2.HomeSubscribeReq,
            bilibili.app.dynamic.v2.dynamic_pb2.HomeSubscribeReply,
        )
        self.LbsPoi = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/LbsPoi',
            bilibili.app.dynamic.v2.dynamic_pb2.LbsPoiReq,
            bilibili.app.dynamic.v2.dynamic_pb2.LbsPoiReply,
        )
        self.LegacyTopicFeed = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/LegacyTopicFeed',
            bilibili.app.dynamic.v2.dynamic_pb2.LegacyTopicFeedReq,
            bilibili.app.dynamic.v2.dynamic_pb2.LegacyTopicFeedReply,
        )
        self.LikeList = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/LikeList',
            bilibili.app.dynamic.v2.dynamic_pb2.LikeListReq,
            bilibili.app.dynamic.v2.dynamic_pb2.LikeListReply,
        )
        self.OfficialAccounts = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/OfficialAccounts',
            bilibili.app.dynamic.v2.dynamic_pb2.OfficialAccountsReq,
            bilibili.app.dynamic.v2.dynamic_pb2.OfficialAccountsReply,
        )
        self.OfficialDynamics = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/OfficialDynamics',
            bilibili.app.dynamic.v2.dynamic_pb2.OfficialDynamicsReq,
            bilibili.app.dynamic.v2.dynamic_pb2.OfficialDynamicsReply,
        )
        self.ReactionList = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/ReactionList',
            bilibili.app.dynamic.v2.dynamic_pb2.ReactionListReq,
            bilibili.app.dynamic.v2.dynamic_pb2.ReactionListReply,
        )
        self.RepostList = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/RepostList',
            bilibili.app.dynamic.v2.dynamic_pb2.RepostListReq,
            bilibili.app.dynamic.v2.dynamic_pb2.RepostListRsp,
        )
        self.SchoolRecommend = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/SchoolRecommend',
            bilibili.app.dynamic.v2.dynamic_pb2.SchoolRecommendReq,
            bilibili.app.dynamic.v2.dynamic_pb2.SchoolRecommendReply,
        )
        self.SchoolSearch = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/SchoolSearch',
            bilibili.app.dynamic.v2.dynamic_pb2.SchoolSearchReq,
            bilibili.app.dynamic.v2.dynamic_pb2.SchoolSearchReply,
        )
        self.SetDecision = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/SetDecision',
            bilibili.app.dynamic.v2.dynamic_pb2.SetDecisionReq,
            bilibili.app.dynamic.v2.dynamic_pb2.NoReply,
        )
        self.SetRecentCampus = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/SetRecentCampus',
            bilibili.app.dynamic.v2.dynamic_pb2.SetRecentCampusReq,
            bilibili.app.dynamic.v2.dynamic_pb2.NoReply,
        )
        self.SubscribeCampus = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/SubscribeCampus',
            bilibili.app.dynamic.v2.dynamic_pb2.SubscribeCampusReq,
            bilibili.app.dynamic.v2.dynamic_pb2.NoReply,
        )
        self.TopicList = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/TopicList',
            bilibili.app.dynamic.v2.dynamic_pb2.TopicListReq,
            bilibili.app.dynamic.v2.dynamic_pb2.TopicListReply,
        )
        self.TopicSquare = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/TopicSquare',
            bilibili.app.dynamic.v2.dynamic_pb2.TopicSquareReq,
            bilibili.app.dynamic.v2.dynamic_pb2.TopicSquareReply,
        )
        self.UnfollowMatch = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/UnfollowMatch',
            bilibili.app.dynamic.v2.dynamic_pb2.UnfollowMatchReq,
            bilibili.app.dynamic.v2.dynamic_pb2.NoReply,
        )
        self.UpdateTabSetting = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.dynamic.v2.Dynamic/UpdateTabSetting',
            bilibili.app.dynamic.v2.dynamic_pb2.UpdateTabSettingReq,
            bilibili.app.dynamic.v2.dynamic_pb2.NoReply,
        )
