# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: google/protobuf/editions/proto/editions_transform_proto3.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'google/protobuf/editions/proto/editions_transform_proto3.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>google/protobuf/editions/proto/editions_transform_proto3.proto\x12\x16protobuf_editions_test\"\xfa\x04\n\x11TestMessageProto3\x12\x14\n\x0cstring_field\x18\x01 \x01(\t\x12\x18\n\x10string_field_utf\x18\x02 \x01(\t\x12\x1a\n\x12string_field_noutf\x18\x03 \x01(\t\x12W\n\x10string_map_field\x18\x04 \x03(\x0b\x32=.protobuf_editions_test.TestMessageProto3.StringMapFieldEntry\x12^\n\x14string_map_field_utf\x18\x05 \x03(\x0b\x32@.protobuf_editions_test.TestMessageProto3.StringMapFieldUtfEntry\x12\x62\n\x16string_map_field_noutf\x18\x06 \x03(\x0b\x32\x42.protobuf_editions_test.TestMessageProto3.StringMapFieldNoutfEntry\x12\x11\n\tint_field\x18\x07 \x03(\x05\x12\x1c\n\x10int_field_packed\x18\x08 \x03(\x05\x42\x02\x10\x01\x12\x1e\n\x12int_field_unpacked\x18\t \x03(\x05\x42\x02\x10\x00\x1a\x35\n\x13StringMapFieldEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x38\n\x16StringMapFieldUtfEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a:\n\x18StringMapFieldNoutfEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.protobuf.editions.proto.editions_transform_proto3_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TESTMESSAGEPROTO3_STRINGMAPFIELDENTRY']._loaded_options = None
  _globals['_TESTMESSAGEPROTO3_STRINGMAPFIELDENTRY']._serialized_options = b'8\001'
  _globals['_TESTMESSAGEPROTO3_STRINGMAPFIELDUTFENTRY']._loaded_options = None
  _globals['_TESTMESSAGEPROTO3_STRINGMAPFIELDUTFENTRY']._serialized_options = b'8\001'
  _globals['_TESTMESSAGEPROTO3_STRINGMAPFIELDNOUTFENTRY']._loaded_options = None
  _globals['_TESTMESSAGEPROTO3_STRINGMAPFIELDNOUTFENTRY']._serialized_options = b'8\001'
  _globals['_TESTMESSAGEPROTO3'].fields_by_name['int_field_packed']._loaded_options = None
  _globals['_TESTMESSAGEPROTO3'].fields_by_name['int_field_packed']._serialized_options = b'\020\001'
  _globals['_TESTMESSAGEPROTO3'].fields_by_name['int_field_unpacked']._loaded_options = None
  _globals['_TESTMESSAGEPROTO3'].fields_by_name['int_field_unpacked']._serialized_options = b'\020\000'
  _globals['_TESTMESSAGEPROTO3']._serialized_start=91
  _globals['_TESTMESSAGEPROTO3']._serialized_end=725
  _globals['_TESTMESSAGEPROTO3_STRINGMAPFIELDENTRY']._serialized_start=554
  _globals['_TESTMESSAGEPROTO3_STRINGMAPFIELDENTRY']._serialized_end=607
  _globals['_TESTMESSAGEPROTO3_STRINGMAPFIELDUTFENTRY']._serialized_start=609
  _globals['_TESTMESSAGEPROTO3_STRINGMAPFIELDUTFENTRY']._serialized_end=665
  _globals['_TESTMESSAGEPROTO3_STRINGMAPFIELDNOUTFENTRY']._serialized_start=667
  _globals['_TESTMESSAGEPROTO3_STRINGMAPFIELDNOUTFENTRY']._serialized_end=725
# @@protoc_insertion_point(module_scope)
