FROM allinurl/goaccess
RUN cd /srv && mkdir geodb && cd geodb \
&& wget https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-ASN.mmdb \
&& wget https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-City.mmdb \
&& wget https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-Country.mmdb