tz Asia/Shanghai
log-format COMBINED
log-file /srv/logs/access.log
output /srv/report/report.html
real-time-html true
ws-url wss://serena.dynv6.net
ssl-cert /srv/certs/fullchain.pem
ssl-key /srv/certs/privkey.pem
hl-header true
config-dialog true
with-mouse true
json-pretty-print true
real-os true
html-refresh 60
geoip-database /srv/logs/GeoLite2-ASN.mmdb
geoip-database /srv/logs/GeoLite2-City.mmdb
geoip-database /srv/logs/GeoLite2-Country.mmdb