# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: bilibili/app/wall/v1/wall.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import bilibili.app.wall.v1.wall_pb2


class WallBase(abc.ABC):

    @abc.abstractmethod
    async def RuleInfo(self, stream: 'grpclib.server.Stream[bilibili.app.wall.v1.wall_pb2.RuleRequest, bilibili.app.wall.v1.wall_pb2.RulesReply]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/bilibili.app.wall.v1.Wall/RuleInfo': grpclib.const.Handler(
                self.RuleInfo,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.app.wall.v1.wall_pb2.RuleRequest,
                bilibili.app.wall.v1.wall_pb2.RulesReply,
            ),
        }


class WallStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.RuleInfo = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.app.wall.v1.Wall/RuleInfo',
            bilibili.app.wall.v1.wall_pb2.RuleRequest,
            bilibili.app.wall.v1.wall_pb2.RulesReply,
        )
