# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: bilibili/main/community/reply/v1/reply.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import google.protobuf.any_pb2
import bilibili.main.community.reply.v1.reply_pb2


class ReplyBase(abc.ABC):

    @abc.abstractmethod
    async def MainList(self, stream: 'grpclib.server.Stream[bilibili.main.community.reply.v1.reply_pb2.MainListReq, bilibili.main.community.reply.v1.reply_pb2.MainListReply]') -> None:
        pass

    @abc.abstractmethod
    async def DetailList(self, stream: 'grpclib.server.Stream[bilibili.main.community.reply.v1.reply_pb2.DetailListReq, bilibili.main.community.reply.v1.reply_pb2.DetailListReply]') -> None:
        pass

    @abc.abstractmethod
    async def DialogList(self, stream: 'grpclib.server.Stream[bilibili.main.community.reply.v1.reply_pb2.DialogListReq, bilibili.main.community.reply.v1.reply_pb2.DialogListReply]') -> None:
        pass

    @abc.abstractmethod
    async def PreviewList(self, stream: 'grpclib.server.Stream[bilibili.main.community.reply.v1.reply_pb2.PreviewListReq, bilibili.main.community.reply.v1.reply_pb2.PreviewListReply]') -> None:
        pass

    @abc.abstractmethod
    async def SearchItemPreHook(self, stream: 'grpclib.server.Stream[bilibili.main.community.reply.v1.reply_pb2.SearchItemPreHookReq, bilibili.main.community.reply.v1.reply_pb2.SearchItemPreHookReply]') -> None:
        pass

    @abc.abstractmethod
    async def SearchItem(self, stream: 'grpclib.server.Stream[bilibili.main.community.reply.v1.reply_pb2.SearchItemReq, bilibili.main.community.reply.v1.reply_pb2.SearchItemReply]') -> None:
        pass

    @abc.abstractmethod
    async def AtSearch(self, stream: 'grpclib.server.Stream[bilibili.main.community.reply.v1.reply_pb2.AtSearchReq, bilibili.main.community.reply.v1.reply_pb2.AtSearchReply]') -> None:
        pass

    @abc.abstractmethod
    async def ReplyInfo(self, stream: 'grpclib.server.Stream[bilibili.main.community.reply.v1.reply_pb2.ReplyInfoReq, bilibili.main.community.reply.v1.reply_pb2.ReplyInfoReply]') -> None:
        pass

    @abc.abstractmethod
    async def UserCallback(self, stream: 'grpclib.server.Stream[bilibili.main.community.reply.v1.reply_pb2.UserCallbackReq, bilibili.main.community.reply.v1.reply_pb2.UserCallbackReply]') -> None:
        pass

    @abc.abstractmethod
    async def ShareRepliesInfo(self, stream: 'grpclib.server.Stream[bilibili.main.community.reply.v1.reply_pb2.ShareRepliesInfoReq, bilibili.main.community.reply.v1.reply_pb2.ShareRepliesInfoResp]') -> None:
        pass

    @abc.abstractmethod
    async def SuggestEmotes(self, stream: 'grpclib.server.Stream[bilibili.main.community.reply.v1.reply_pb2.SuggestEmotesReq, bilibili.main.community.reply.v1.reply_pb2.SuggestEmotesResp]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/bilibili.main.community.reply.v1.Reply/MainList': grpclib.const.Handler(
                self.MainList,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.main.community.reply.v1.reply_pb2.MainListReq,
                bilibili.main.community.reply.v1.reply_pb2.MainListReply,
            ),
            '/bilibili.main.community.reply.v1.Reply/DetailList': grpclib.const.Handler(
                self.DetailList,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.main.community.reply.v1.reply_pb2.DetailListReq,
                bilibili.main.community.reply.v1.reply_pb2.DetailListReply,
            ),
            '/bilibili.main.community.reply.v1.Reply/DialogList': grpclib.const.Handler(
                self.DialogList,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.main.community.reply.v1.reply_pb2.DialogListReq,
                bilibili.main.community.reply.v1.reply_pb2.DialogListReply,
            ),
            '/bilibili.main.community.reply.v1.Reply/PreviewList': grpclib.const.Handler(
                self.PreviewList,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.main.community.reply.v1.reply_pb2.PreviewListReq,
                bilibili.main.community.reply.v1.reply_pb2.PreviewListReply,
            ),
            '/bilibili.main.community.reply.v1.Reply/SearchItemPreHook': grpclib.const.Handler(
                self.SearchItemPreHook,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.main.community.reply.v1.reply_pb2.SearchItemPreHookReq,
                bilibili.main.community.reply.v1.reply_pb2.SearchItemPreHookReply,
            ),
            '/bilibili.main.community.reply.v1.Reply/SearchItem': grpclib.const.Handler(
                self.SearchItem,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.main.community.reply.v1.reply_pb2.SearchItemReq,
                bilibili.main.community.reply.v1.reply_pb2.SearchItemReply,
            ),
            '/bilibili.main.community.reply.v1.Reply/AtSearch': grpclib.const.Handler(
                self.AtSearch,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.main.community.reply.v1.reply_pb2.AtSearchReq,
                bilibili.main.community.reply.v1.reply_pb2.AtSearchReply,
            ),
            '/bilibili.main.community.reply.v1.Reply/ReplyInfo': grpclib.const.Handler(
                self.ReplyInfo,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.main.community.reply.v1.reply_pb2.ReplyInfoReq,
                bilibili.main.community.reply.v1.reply_pb2.ReplyInfoReply,
            ),
            '/bilibili.main.community.reply.v1.Reply/UserCallback': grpclib.const.Handler(
                self.UserCallback,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.main.community.reply.v1.reply_pb2.UserCallbackReq,
                bilibili.main.community.reply.v1.reply_pb2.UserCallbackReply,
            ),
            '/bilibili.main.community.reply.v1.Reply/ShareRepliesInfo': grpclib.const.Handler(
                self.ShareRepliesInfo,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.main.community.reply.v1.reply_pb2.ShareRepliesInfoReq,
                bilibili.main.community.reply.v1.reply_pb2.ShareRepliesInfoResp,
            ),
            '/bilibili.main.community.reply.v1.Reply/SuggestEmotes': grpclib.const.Handler(
                self.SuggestEmotes,
                grpclib.const.Cardinality.UNARY_UNARY,
                bilibili.main.community.reply.v1.reply_pb2.SuggestEmotesReq,
                bilibili.main.community.reply.v1.reply_pb2.SuggestEmotesResp,
            ),
        }


class ReplyStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.MainList = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.main.community.reply.v1.Reply/MainList',
            bilibili.main.community.reply.v1.reply_pb2.MainListReq,
            bilibili.main.community.reply.v1.reply_pb2.MainListReply,
        )
        self.DetailList = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.main.community.reply.v1.Reply/DetailList',
            bilibili.main.community.reply.v1.reply_pb2.DetailListReq,
            bilibili.main.community.reply.v1.reply_pb2.DetailListReply,
        )
        self.DialogList = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.main.community.reply.v1.Reply/DialogList',
            bilibili.main.community.reply.v1.reply_pb2.DialogListReq,
            bilibili.main.community.reply.v1.reply_pb2.DialogListReply,
        )
        self.PreviewList = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.main.community.reply.v1.Reply/PreviewList',
            bilibili.main.community.reply.v1.reply_pb2.PreviewListReq,
            bilibili.main.community.reply.v1.reply_pb2.PreviewListReply,
        )
        self.SearchItemPreHook = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.main.community.reply.v1.Reply/SearchItemPreHook',
            bilibili.main.community.reply.v1.reply_pb2.SearchItemPreHookReq,
            bilibili.main.community.reply.v1.reply_pb2.SearchItemPreHookReply,
        )
        self.SearchItem = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.main.community.reply.v1.Reply/SearchItem',
            bilibili.main.community.reply.v1.reply_pb2.SearchItemReq,
            bilibili.main.community.reply.v1.reply_pb2.SearchItemReply,
        )
        self.AtSearch = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.main.community.reply.v1.Reply/AtSearch',
            bilibili.main.community.reply.v1.reply_pb2.AtSearchReq,
            bilibili.main.community.reply.v1.reply_pb2.AtSearchReply,
        )
        self.ReplyInfo = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.main.community.reply.v1.Reply/ReplyInfo',
            bilibili.main.community.reply.v1.reply_pb2.ReplyInfoReq,
            bilibili.main.community.reply.v1.reply_pb2.ReplyInfoReply,
        )
        self.UserCallback = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.main.community.reply.v1.Reply/UserCallback',
            bilibili.main.community.reply.v1.reply_pb2.UserCallbackReq,
            bilibili.main.community.reply.v1.reply_pb2.UserCallbackReply,
        )
        self.ShareRepliesInfo = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.main.community.reply.v1.Reply/ShareRepliesInfo',
            bilibili.main.community.reply.v1.reply_pb2.ShareRepliesInfoReq,
            bilibili.main.community.reply.v1.reply_pb2.ShareRepliesInfoResp,
        )
        self.SuggestEmotes = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bilibili.main.community.reply.v1.Reply/SuggestEmotes',
            bilibili.main.community.reply.v1.reply_pb2.SuggestEmotesReq,
            bilibili.main.community.reply.v1.reply_pb2.SuggestEmotesResp,
        )
