# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bilibili/live/general/interfaces/v1/interfaces.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bilibili/live/general/interfaces/v1/interfaces.proto',
  package='bilibili.live.general.interfaces.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n4bilibili/live/general/interfaces/v1/interfaces.proto\x12#bilibili.live.general.interfaces.v1\"d\n\x10GetOnlineRankReq\x12\x0c\n\x04ruid\x18\x01 \x01(\x03\x12\x0f\n\x07room_id\x18\x02 \x01(\x03\x12\x0c\n\x04page\x18\x03 \x01(\x03\x12\x11\n\tpage_size\x18\x04 \x01(\x03\x12\x10\n\x08platform\x18\x05 \x01(\t\"\xaa\x02\n\x11GetOnlineRankResp\x12S\n\x04item\x18\x01 \x01(\x0b\x32\x45.bilibili.live.general.interfaces.v1.GetOnlineRankResp.OnlineRankItem\x12\x12\n\nonline_num\x18\x02 \x01(\x03\x1a\xab\x01\n\x0eOnlineRankItem\x12\x0b\n\x03uid\x18\x01 \x01(\x03\x12\r\n\x05uname\x18\x02 \x01(\t\x12\x0c\n\x04\x66\x61\x63\x65\x18\x03 \x01(\t\x12\x16\n\x0e\x63ontinue_watch\x18\x04 \x01(\x03\x12\x42\n\nmedal_info\x18\x05 \x01(\x0b\x32..bilibili.live.general.interfaces.v1.MedalInfo\x12\x13\n\x0bguard_level\x18\x06 \x01(\x03\"\xb8\x01\n\tMedalInfo\x12\x13\n\x0bguard_level\x18\x01 \x01(\x03\x12\x19\n\x11medal_color_start\x18\x02 \x01(\x03\x12\x17\n\x0fmedal_color_end\x18\x03 \x01(\x03\x12\x1a\n\x12medal_color_border\x18\x04 \x01(\x03\x12\x12\n\nmedal_name\x18\x05 \x01(\t\x12\r\n\x05level\x18\x06 \x01(\x03\x12\x11\n\ttarget_id\x18\x07 \x01(\x03\x12\x10\n\x08is_light\x18\x08 \x01(\x03\x62\x06proto3'
)




_GETONLINERANKREQ = _descriptor.Descriptor(
  name='GetOnlineRankReq',
  full_name='bilibili.live.general.interfaces.v1.GetOnlineRankReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ruid', full_name='bilibili.live.general.interfaces.v1.GetOnlineRankReq.ruid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='room_id', full_name='bilibili.live.general.interfaces.v1.GetOnlineRankReq.room_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='page', full_name='bilibili.live.general.interfaces.v1.GetOnlineRankReq.page', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='page_size', full_name='bilibili.live.general.interfaces.v1.GetOnlineRankReq.page_size', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='platform', full_name='bilibili.live.general.interfaces.v1.GetOnlineRankReq.platform', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=193,
)


_GETONLINERANKRESP_ONLINERANKITEM = _descriptor.Descriptor(
  name='OnlineRankItem',
  full_name='bilibili.live.general.interfaces.v1.GetOnlineRankResp.OnlineRankItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='bilibili.live.general.interfaces.v1.GetOnlineRankResp.OnlineRankItem.uid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uname', full_name='bilibili.live.general.interfaces.v1.GetOnlineRankResp.OnlineRankItem.uname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='face', full_name='bilibili.live.general.interfaces.v1.GetOnlineRankResp.OnlineRankItem.face', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='continue_watch', full_name='bilibili.live.general.interfaces.v1.GetOnlineRankResp.OnlineRankItem.continue_watch', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='medal_info', full_name='bilibili.live.general.interfaces.v1.GetOnlineRankResp.OnlineRankItem.medal_info', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='guard_level', full_name='bilibili.live.general.interfaces.v1.GetOnlineRankResp.OnlineRankItem.guard_level', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=323,
  serialized_end=494,
)

_GETONLINERANKRESP = _descriptor.Descriptor(
  name='GetOnlineRankResp',
  full_name='bilibili.live.general.interfaces.v1.GetOnlineRankResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='item', full_name='bilibili.live.general.interfaces.v1.GetOnlineRankResp.item', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='online_num', full_name='bilibili.live.general.interfaces.v1.GetOnlineRankResp.online_num', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_GETONLINERANKRESP_ONLINERANKITEM, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=494,
)


_MEDALINFO = _descriptor.Descriptor(
  name='MedalInfo',
  full_name='bilibili.live.general.interfaces.v1.MedalInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='guard_level', full_name='bilibili.live.general.interfaces.v1.MedalInfo.guard_level', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='medal_color_start', full_name='bilibili.live.general.interfaces.v1.MedalInfo.medal_color_start', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='medal_color_end', full_name='bilibili.live.general.interfaces.v1.MedalInfo.medal_color_end', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='medal_color_border', full_name='bilibili.live.general.interfaces.v1.MedalInfo.medal_color_border', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='medal_name', full_name='bilibili.live.general.interfaces.v1.MedalInfo.medal_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='level', full_name='bilibili.live.general.interfaces.v1.MedalInfo.level', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target_id', full_name='bilibili.live.general.interfaces.v1.MedalInfo.target_id', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_light', full_name='bilibili.live.general.interfaces.v1.MedalInfo.is_light', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=497,
  serialized_end=681,
)

_GETONLINERANKRESP_ONLINERANKITEM.fields_by_name['medal_info'].message_type = _MEDALINFO
_GETONLINERANKRESP_ONLINERANKITEM.containing_type = _GETONLINERANKRESP
_GETONLINERANKRESP.fields_by_name['item'].message_type = _GETONLINERANKRESP_ONLINERANKITEM
DESCRIPTOR.message_types_by_name['GetOnlineRankReq'] = _GETONLINERANKREQ
DESCRIPTOR.message_types_by_name['GetOnlineRankResp'] = _GETONLINERANKRESP
DESCRIPTOR.message_types_by_name['MedalInfo'] = _MEDALINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetOnlineRankReq = _reflection.GeneratedProtocolMessageType('GetOnlineRankReq', (_message.Message,), {
  'DESCRIPTOR' : _GETONLINERANKREQ,
  '__module__' : 'bilibili.live.general.interfaces.v1.interfaces_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.live.general.interfaces.v1.GetOnlineRankReq)
  })
_sym_db.RegisterMessage(GetOnlineRankReq)

GetOnlineRankResp = _reflection.GeneratedProtocolMessageType('GetOnlineRankResp', (_message.Message,), {

  'OnlineRankItem' : _reflection.GeneratedProtocolMessageType('OnlineRankItem', (_message.Message,), {
    'DESCRIPTOR' : _GETONLINERANKRESP_ONLINERANKITEM,
    '__module__' : 'bilibili.live.general.interfaces.v1.interfaces_pb2'
    # @@protoc_insertion_point(class_scope:bilibili.live.general.interfaces.v1.GetOnlineRankResp.OnlineRankItem)
    })
  ,
  'DESCRIPTOR' : _GETONLINERANKRESP,
  '__module__' : 'bilibili.live.general.interfaces.v1.interfaces_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.live.general.interfaces.v1.GetOnlineRankResp)
  })
_sym_db.RegisterMessage(GetOnlineRankResp)
_sym_db.RegisterMessage(GetOnlineRankResp.OnlineRankItem)

MedalInfo = _reflection.GeneratedProtocolMessageType('MedalInfo', (_message.Message,), {
  'DESCRIPTOR' : _MEDALINFO,
  '__module__' : 'bilibili.live.general.interfaces.v1.interfaces_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.live.general.interfaces.v1.MedalInfo)
  })
_sym_db.RegisterMessage(MedalInfo)


# @@protoc_insertion_point(module_scope)
